### ISSUE TITLE
Support ConstantBuffer layout info?

### ISSUE THREAD

**Issue by BobbyBao** [DiligentGraphics/DiligentCore#1]

**Comment by DiligentGraphics** [comment]
Could you please elaborate on this?

**Comment by BobbyBao** [comment]
I am implementing a extensible material system, i need to get members of a constant buffer, like type offset, size. When add a new shader, loaders auto add shader parameters to the material, instead of change the ConstantBuffer struct in cpp source code.

**Comment by BobbyBao** [comment]
The IShaderVariable cannot use on a single vector parament

**Comment by DiligentGraphics** [comment]
OK, I see. The reason that IShaderVariable cannot be used on a single parameter is because GPUs work on a buffer granularity. On the other hand, shader reflection system knows the structure of every buffer and that information can be exposed. I'll add this functionality to my to-do list.

**Comment by DiligentGraphics** [comment]
Dup of https://github.com/DiligentGraphics/DiligentCore/issues/92
