### ISSUE TITLE
Question about DvpVerifyDynamicAllocation error.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#100]
I am constantly getting this error on Direct3D 12 & Vulkan Render APIs, is there any more info about it?
I don't really know what is causing it and the code runs well without problems in Direct3D 11 API.

```
Diligent Engine: ERROR: Debug assertion failed in Diligent::BufferVkImpl::DvpVerifyDynamicAllocation(), file BufferVkImpl.cpp, line 392:
Dynamic allocation of dynamic buffer 'LightCB' in frame 1 is out-of-date. Note: contents of all dynamic resources is discarded at the end of every frame. A buffer must be mapped before its first use in any frame.
```

**Comment by DiligentGraphics** [comment]
Well, like the error message says: you need to first map the dynamic buffer in every frame (i.e. after the call to present) and fill it with data before you can use it. If you don't need to map the buffer every frame, most likely it doesn't need to be dynamic

**Comment by zlixine** [comment]
> (i.e. after the call to present)

It turns out after the engine creates the buffer it map it and fill it with data and that what caused the error.

Thanks very much!
