### ISSUE TITLE
Questions regarding the include headers directory from external project

### ISSUE THREAD

**Issue by hydexon** [DiligentGraphics/DiligentCore#104]
Since i'm using the Non-CMake integration approach in my project, i was doubting about the headers directory structure since every DiligentCore Module headers has their own "interface" directories and i have to specify it everytime i want to include an particular header in my code. It's correct right?.

Also building the INSTALL target in Linux creates in the root directory (instead of DiligentCore proper headers and libraries, but its another subfolder called DiligentCore), the include,libraries and share directories for SPIR-V CROSS.

**Comment by DiligentGraphics** [comment]
You should add the path to the `headers` folder and then use relative directories:

```cpp
#include "Graphics/GraphicsEngine/interface/RenderDevice.h"
#include "Graphics/GraphicsEngine/interface/DeviceContext.h"
#include "Graphics/GraphicsEngine/interface/SwapChain.h"
```
Alternatively, you can add `Graphics/GraphicsEngine/interface` directory as it contains the files that are most commonly used.

As to SPIRV-Cross libraries and headers, this happens because SPIRV-Cross project does not allow disabling installation.
I added a feature request: https://github.com/KhronosGroup/SPIRV-Cross/issues/1153

**Comment by hydexon** [comment]
Alright, thanks for the aclaration. an side question, the HLSL library, is really needed or how is an required dependency compared to glslang in Non-Windows side?. Thanks.

**Comment by DiligentGraphics** [comment]
Diligent uses HLSL as primary shading language on all platforms, including Linux, Mac, Android and iOS, so the library is required to compile HLSL into SPIR-V. If you do not need to use run-time shader compilation, you can use [DILIGENT_NO_GLSLANG build option](https://github.com/DiligentGraphics/DiligentEngine#build-options) to disable all glslang-related components including HLSL library.

**Comment by DiligentGraphics** [comment]
SPIRV-Cross team added option to disable the installation, which is used in [this change](https://github.com/DiligentGraphics/DiligentEngine/commit/4ac6252d198388a3627d2d1182f747d0c32c30b1).
Do not forget to recursively update all submodules and clear CMake cache (ideally delete all build files)
