### ISSUE TITLE
Dump GPU Capabilities on Initialization

### ISSUE THREAD

**Issue by julianxhokaxhiu** [DiligentGraphics/DiligentCore#110]
**This is a feature request.**

Hi,

is it possible to add a dump of the GPU Capabilities after initialization, like [bgfx does](https://github.com/bkaradzic/bgfx/blob/master/src/bgfx.cpp#L1488)? This would greatly enhance developers experience by allowing us debugging the end user environment very easily, in order to fix potential bugs that may arise during runtime.

Thank you in advance,
Julian

---

[example.log](https://github.com/DiligentGraphics/DiligentCore/files/4007533/example.log)

**Comment by DiligentGraphics** [comment]
As long as these settings are exposed to the application, it is free to do whatever it needs to including dumping them into the log. It is not the responsibility of the graphics API.
