### ISSUE TITLE
Investigate running automated tests on CI server for OpenGL

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentCore#112]
This requires using some sort of software implementation such as [llvmpipe](https://www.mesa3d.org/llvmpipe.html). Unfortunately, llvmpipe only implements OpenGL 3.3, though missing features might not be a bing problem, see [here](https://mesamatrix.net).

**Comment by TheMostDiligent** [comment]
OpenGL tests enabled on Linux in https://github.com/DiligentGraphics/DiligentCore/commit/1f7a37a5666385eae92c03f34fe3fcab80ee1de0
