### ISSUE TITLE
Multiple swapchains without primary swapchain?

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#116]
Hello, we're having great experience using DiligentEngine recently. 

There's one tiny thing that we're not really sure if we're doing it wrong, or we should request some addition in DiligentCore itself. 

Our requirement is that we sometimes need different swapchains displaying different scenes using the same render device. There's one example in the tutorials. However our requirement is different from it in that the window/swapchain list is dynamically managed, meaning that we can't really set one of them primary. 

So we're setting all of their `IsPrimary` to false. This works fine on dx12 backend (now we call FinishFrame() and ReleaseStaleResources() ourselves for each swapchain after drawing, following the code in dx12 backend). 

However this seems doesn't work on dx11 backend. The screen is white (most of the time).  We investigated it a little, and found that the `CommitRenderTargets` cannot be called anywhere. We're not sure whether this should be considered a bug, or a new API should be added, or our design is fundamentally flawed... We've also not tested this on other backends yet, and not sure about their status.

**Comment by DiligentGraphics** [comment]
Your usage scenario is correct. For DX11 backend, there is very little difference between primary and secondary swap chains, so not sure why it does not work in your case. When tutorial 15 is running, `CommitRenderTargets` is called every frame for every swap chain.

Not sure what the problem is. Do you have any errors/warnings in the debug output?

**Comment by crlf0710** [comment]
Thank you for your confirmation and fast reply! I was using the tag version 2.4.c. I found the dubious primary-swapchain-only `CommitRenderTargets()` call was removed in https://github.com/DiligentGraphics/DiligentCore/commit/71595b9099ad70b474502ca3b16c2da7050cb6a8#diff-602d9ca4cfa20a8c9c584a71c25b45bdL145
So maybe it's time for me to pull recent changes and try again. I'll update with my findings on monday.

**Comment by DiligentGraphics** [comment]
Oh, yes. That version is quite out-of-date now and there were some changes to swap chains. Please get the latest version and check if it works now.
In particular, `SetRenderTargets(0, nullptr, nullptr)` call does not bind the default render targets anymore. The render target and depth stencil must be explicitly requested from the swap chain now.

**Comment by DiligentGraphics** [comment]
Also note that an application must bind render targets every frame as present call unbinds all swap chain render targets.

**Comment by crlf0710** [comment]
Hooray! I switched to the newest commit and everything works just as expected. 

Thank you! Eager to see your next stable release.
