### ISSUE TITLE
Diligent Does not compile for ios when using Apple Clang 11

### ISSUE THREAD

**Issue by kevintan82** [DiligentGraphics/DiligentCore#120]
Hi,

I just started using Diligent and I was trying to get it to compile for IOS using XCode 11. CMake failed in generating a valid XCode project.

From my understanding Apple Clang from version 11 onwards drops support for 32 bit applications. as such arm7 and arm7s are no longer valid architectures.

I did a minor change to ios.toolchain.cmake to omit the architectures for XCode 11. The change can be viewed in the link below.

https://github.com/kevintan82/DiligentCore/commit/dadcd0f7a89cef02ce5406b0b3500d9028dcd541

Compilation now works for my machine. Thank you for your time.

**Comment by DiligentGraphics** [comment]
Hi!
Did you use `-DIOS_PLATFORM=OS64` option? This should make it [use only 64-bit architectures](https://github.com/DiligentGraphics/DiligentCore/blob/master/ios.toolchain.cmake#L153).

**Comment by kevintan82** [comment]
Hi, 

Thank you for pointing me in the direction for the preferred method of fixing the problem.

**Comment by DiligentGraphics** [comment]
Looks like this problem is solved now, so should we close the issue?
