### ISSUE TITLE
Using float3 int16/uint16 vertex attributes on Vulkan

### ISSUE THREAD

**Issue by dolphineye** [DiligentGraphics/DiligentCore#122]
Hi,

In our project, we have been using `float3` vertex attributes encoded as normalised uint16s. This works properly with OpenGL & OpenGL ES backends, but it seems that the mapping is not there for the Vulkan/MoltenVK backend.

Source: https://github.com/DiligentGraphics/DiligentCore/blob/ca9aeaf93afaa610aab1ce585daa20ffcf27d3a7/Graphics/GraphicsEngineVulkan/src/VulkanTypeConversions.cpp#L557

I tried to add: `case 3: return VK_FORMAT_R16G16B16_UNORM;` for testing and it seems this works like a charm at least on iOS w/ MoltenVK. Is there any particular reason for not having a mapping for `float3s`?

Thanks for helping!

**Comment by TheMostDiligent** [comment]
The main reason was that 3-component 8-bit and 16-bit formats are not supported by D3D11 and D3D12, but I guess it is OK to allow them in Vulkan and OpenGL only https://github.com/DiligentGraphics/DiligentCore/commit/a1e3647ecbd8ca99ee42212feca449f9696bdd4c

**Comment by dolphineye** [comment]
Thanks!
