### ISSUE TITLE
Potential issue in common/BasicMath.hpp

### ISSUE THREAD

**Issue by axoloto** [DiligentGraphics/DiligentCore#126]
Hi guys! 

I am sorry to bother you with this and I might be wrong, but I think the function OrthoOffCenter may contain a small glitch in interface/common/BasicMath.hpp. It looks like it should be:
        auto _22 = (bIsGL ? 2 : 1) / ( zNear - zFar);
And NOT
        auto _22 = (bIsGL ? 2 : 1) / ( zFar - zNear);

Thanks a lot for what you are doing! Keep up the good work!

Adrien

**Comment by TheMostDiligent** [comment]
At the low level, there is only one difference between OpenGL and other native APIs: OpenGL uses [-1, +1] for normalized device Z coordinate, while all other APIs use [0, +1].
The direction of camera Z axis (either positive or negative) is a convention. Diligent uses Direct3D-style coordinate system where camera is looking along positive Z axis even when running in OpenGL mode, so it should not be inverted.
Please also take a look at [this question](https://github.com/DiligentGraphics/DiligentEngine/issues/75).

**Comment by TheMostDiligent** [comment]
Also please take a look at [these tests](https://github.com/DiligentGraphics/DiligentCore/blob/master/Tests/DiligentCoreTest/src/Common/MathLibTest.cpp#L823)

**Comment by axoloto** [comment]
Sorry I totally forgot to answer you, thanks a lot for your detailed explanation. I thought that the sign was not OpenGL/Direct3D dependent. After few tries, I realized it worked correctly with the current implementation, at least with OpenGL. You can close this ticket. Thanks
