### ISSUE TITLE
Build with Ninja failed about backend DirectX12

### ISSUE THREAD

**Issue by juteman** [DiligentGraphics/DiligentCore#127]
everything get ok when I use cmake  generates visual studio sln flie, it build all to lib.
But when I generate with Ninja build system. It will get:
> `FAILED: Graphics/GraphicsEngineD3D12/CMakeFiles/Diligent-GraphicsEngineD3D12-static.dir/src/GenerateMips.cpp.obj
D:\PROGRA~1\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\cl.exe  /nologo /TP -DD3D11_SUPPORTED=1 -DD3D12_SUPPORTED=1 -DDILIGENT_DEBUG -DDILIGENT_DEVELOPMENT -DGLES_SUPPORTED=0 -DGL_SUPPORTED=1 -DMETAL_SUPPORTED=0 -DPLATFORM_WIN32=1 -DUSE_D3D12_LOADER=1 -DVULKAN_SUPPORTED=1 -IGraphics\GraphicsEngineD3D12\CompiledShaders -I..\Graphics\GraphicsEngineD3D12\include -I..\Common\interface -I..\Platforms\Win32\interface -I..\Platforms\Basic\interface -I..\Primitives\interface -I..\Platforms\interface -I..\Graphics\GraphicsEngineD3DBase\include -I..\Graphics\GraphicsEngine\include -I..\Graphics\GraphicsEngine\interface -I..\Graphics\GraphicsAccessories\interface -I..\Graphics\GraphicsEngineD3DBase\interface -I..\Graphics\GraphicsEngineNextGenBase\include -I..\Graphics\GraphicsEngineD3D12\interface /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /W4 /wd4100 /wd4505 /wd4201 /showIncludes /FoGraphics\GraphicsEngineD3D12\CMakeFiles\Diligent-GraphicsEngineD3D12-static.dir\src\GenerateMips.cpp.obj /FdGraphics\GraphicsEngineD3D12\CMakeFiles\Diligent-GraphicsEngineD3D12-static.dir\Diligent-GraphicsEngineD3D12-static.pdb /FS -c ..\Graphics\GraphicsEngineD3D12\src\GenerateMips.cpp
..\Graphics\GraphicsEngineD3D12\src\GenerateMips.cpp(54): fatal error C1083:  can not open the include file: “GenerateMips/GenerateMipsLinearCS.h”: No such file or directory
`

And I read the source code about the GenerateMips.cpp and the CMakeList.txt file.It seems that the header file was build by  Shader file HLSL. I can search and find HLSL file but can't find GenerateMipsLinearCS.h both project folder and build folder( it can find in build folder when build with sln).
After that I change D3D12_SUPPORTED: TRUE to D3D12_SUPPORTED: FALSE by cmake options, the ninja build it success.
the enviroment is fine. I can exec the sample with backend DirecX12 build by sln.

**Comment by TheMostDiligent** [comment]
Yes, it is a known issue. The file is currently generated as part of Visual Studio build process by using VS-specific instructions. On other build systems these instructions are ignored an the file is not generated.
