### ISSUE TITLE
BasicMath.hpp - Can use in my lib, but fails when referencing include.

### ISSUE THREAD

**Issue by VividCoder** [DiligentGraphics/DiligentCore#131]
I have a basic lib up and running, that uses diligent. This compiles fine.
However, when I include a file from this lib into a normal desktop app, I get a string of errors regarding BasicMaths.hpp - from which I use float2/3/4.

Here are the errors,

`1>C:\Git\VividEngine\Project\OpenSourceContrib\DiligentEngine\DiligentCore\Common\interface\BasicMath.hpp(1594,12): error C2988: unrecognizable template declaration/definition
`
`1>C:\Git\VividEngine\Project\OpenSourceContrib\DiligentEngine\DiligentCore\Common\interface\BasicMath.hpp(1594,12): error C2059: syntax error: 'const'
`
And several similar. Everything else compiles fine.

Here is the file that references basicmath.hpp

`#pragma once

#include "Common/interface/RefCntAutoPtr.hpp"
#include "Common/interface/BasicMath.hpp"

using namespace std;
using namespace Diligent;

struct Vertex2D {

	float3 Pos;
	float2 Uv;
	float4 Col;

};
`

I'm using Visual Studio 2019 - Latest version(Community edition)

**Comment by TheMostDiligent** [comment]
I tried your code and it compiles fine on VS2019.
There is a [test file](https://github.com/DiligentGraphics/DiligentCore/blob/master/Tests/IncludeTest/Common/BasicMathH_test.cpp) for every core header that tests that the header can be included by itself and it [compiles OK](https://ci.appveyor.com/project/DiligentGraphics/diligentcore/build/job/7quuuiqn9de2i4j1?fullLog=true#L132). This appears like some configuration problem on your side.

**Comment by VividCoder** [comment]
Hi,

Thanks. Yeah to explain a bit better, the library I'm using it in, compiles fine, even with the code using the float2/3/4 classes. However, my desktop app includes one of my includes, which it's self include basic math, and the errors all happen there.

Maybe you could try my actual project? It's https://github.com/VividCoder/Twilight3D - it's a lib, and a desktop app, it compiles the lib, but the above error happens in the app it's self?

**Comment by TheMostDiligent** [comment]
OK, if it is included in your file, try removing 
```cpp
using namespace std;
using namespace Diligent;
```

**Comment by VividCoder** [comment]
Just tried it and makes no difference in the app. Here is what I changed it to.

`
#pragma once

//#include "Graphics/GraphicsTools/interface/MapHelper.hpp"
//#include "Graphics/GraphicsTools/interface/GraphicsUtilities.h"
#include <vector>
#include "pch.h"

#include "Graphics//GraphicsEngine/interface/EngineFactory.h"
#include "Graphics/GraphicsEngineD3D11/interface/EngineFactoryD3D11.h"
#include "Graphics/GraphicsEngineD3D12/interface/EngineFactoryD3D12.h"
#include "Graphics/GraphicsEngineOpenGL/interface/EngineFactoryOpenGL.h"
#include "Graphics/GraphicsEngineVulkan/interface/EngineFactoryVk.h"

#include "Graphics/GraphicsEngine/interface/RenderDevice.h"
#include "Graphics/GraphicsEngine/interface/DeviceContext.h"
#include "Graphics/GraphicsEngine/interface/SwapChain.h"

#include "Common/interface/RefCntAutoPtr.hpp"
#include "Common/interface/BasicMath.hpp"



struct Vertex2D {

	Diligent::float3 Pos;
	Diligent::float2 Uv;
	Diligent::float4 Col;

};`

Exactly the same error in the desktop app, the lib continues to compile OK.

**Comment by TheMostDiligent** [comment]
Do you `#include<Windows.h>` somewhere? If so, you need to
```
#define NOMINMAX
```
before including it.

**Comment by VividCoder** [comment]
Yeah already there, here is that part of my main include.

`#ifndef NOMINMAX
#    define NOMINMAX
#endif
#include <Windows.h>

#ifndef PLATFORM_WIN32
#    define PLATFORM_WIN32 1
#endif
`

**Comment by TheMostDiligent** [comment]
Try to define NOMINMAX as global project setting. Sometimes some other files (e.g. d3d11.h) include<Windows.h>

**Comment by VividCoder** [comment]
Yes that worked, thanks.
