### ISSUE TITLE
cmake targets does not export includes.

### ISSUE THREAD

**Issue by markusgod** [DiligentGraphics/DiligentCore#132]
![screenshot](https://i.imgur.com/NOe9FZp.png)
From readme.me 
```Alternatively, you can link against static (as well as shared) versions of libraries using target_link_libraries() command. In this case there is no need to explicitly add DiligentCore to the list of include directories as the targets export all required include paths. ```
Clion suggests directly include `#include <EngineFactoryVk.h>`, but this is probably wrong.

**Comment by TheMostDiligent** [comment]
It [exports](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/CMakeLists.txt#L134) [interface](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/CMakeLists.txt#L208) folder, so CLion is correct.
I do not indeed export the root folder of the include trerr.
