### ISSUE TITLE
GetStaticVariableByName is giving null in a Pixel Shader Type

### ISSUE THREAD

**Issue by rbnpontes** [DiligentGraphics/DiligentCore#134]
Hi folks,
I am currently trying to modify one of the examples in the tutorial and am having a problem with the GetStaticVariableByName function.
For some reason this function only returns an object only when its type is `SHADER_TYPE_VERTEX`.

These are my codes used:
**Vertex Shader**
`https://gist.github.com/rbnpontes/ac3f276c3b98243c2a61ceb94810ed67`
**Pixel Shader**
`https://gist.github.com/rbnpontes/69ec0ddfa31262b169379fd952b8b39b`
**Pipeline Initialization**
`https://gist.github.com/rbnpontes/9058b6e8265a4befc91bf852592d7dbe`

My Configs:
- Windows 10 - Home
- CMake 3.16.3
- Visual Studio 2019
- Intel (R) HD Graphics 620
- Debug Ouput:
`Diligent Engine: Info: User-defined allocator is not provided. Using default allocator.`

**Comment by TheMostDiligent** [comment]
Constant buffer `PSConstants` is never used in your pixel shader and the compiler optimized it out.

**Comment by rbnpontes** [comment]
But in the example of `Tutorial07_GeometryShader` I saw that it was used, specifically on line `238` ?

Forgive me for my ignorance, I'm relatively new to the subject!

**Comment by TheMostDiligent** [comment]
What I mean is that you pixel shader body (the `main` function) does not ever use members of `PSConstants` cbuffer. Microsoft HLSL compiler optimizes all unused variables and they are as if they were not declared in the shader.
All samples and tutorials do actually use constants buffers, textures and other resources they declare in the shaders.

**Comment by rbnpontes** [comment]
Aaah, Thanks
