### ISSUE TITLE
Render blend modes?

### ISSUE THREAD

**Issue by VividCoder** [DiligentGraphics/DiligentCore#135]
Hi,

I am at the stage in my project I want multiple lights. I usually achieve this by rendering the scene one light at a time, and that works in OpenGL etc thanks to changing the render blend mode, to additive or modulate. But I can't seem to find where in the Diligent API this would be possible.

Any samples I may have missed? If not, could someone tell me the class/es that make this possible?

Thanks.

**Comment by VividCoder** [comment]
Sorry I figured it out. The below goes into the graphics pipeline of your choice, just in case anyone doesn't know. closing.

 BlendStateDesc BlendState[NumStates];
    BlendState[1].RenderTargets[0].BlendEnable = true;
    BlendState[1].RenderTargets[0].SrcBlend    = BLEND_FACTOR_SRC_ALPHA;
    BlendState[1].RenderTargets[0].DestBlend   = BLEND_FACTOR_INV_SRC_ALPHA;

**Comment by VividCoder** [comment]
Sorry, despite it being how it's done in the samples, the above has no effect on the renderering. I just see the first render, not anything after. I've tried disabling depth testing to no avail.

**Comment by VividCoder** [comment]
Found the issue. this,

   devCon->CommitShaderResources(s1->GetBinding(), RESOURCE_STATE_TRANSITION_MODE_TRANSITION);

needs to happen just before you render the second pass.

**Comment by TheMostDiligent** [comment]
Note that [gitter char](https://gitter.im/diligent-engine/Lobby?source=orgpage) could be a better place for questions like this one.

**Comment by VividCoder** [comment]
Sorry, I'll use gitter in the future for such things.
