### ISSUE TITLE
GL_TEXTURE_EXTERNAL_OES for ARCore

### ISSUE THREAD

**Issue by adamikandras** [DiligentGraphics/DiligentCore#136]
Hey Guys!

Awesome work, very nice code structure, and great support (You already fixed an earlier issue of mine with Android build).
I've got a question about the Android (or more generally the OpenGLES) version.
I'd like to implement an AR app based on ARCore and for the background camera image renderer it requires the [GL_TEXTURE_EXTERNAL_OES target](https://developers.google.com/ar/reference/c/group/session#arsession_setcameratexturename) which is not available out-of-the box in this engine. I figured that if there would be a texture type for that (similar to `class Texture2D_OGL final : public TextureBaseGL`) it could maybe fit in the architecture. Of course it comes from a 15 minute debug session, so I'm not too confident, but when I tried to use a manually assembled GLES textureid with `CreateTextureFromGLHandle`, the resulting ASSERT comes from using the wrong texture target when trying to squeeze my `GL_TEXTURE_EXTERNAL_OES` into a `Texture2D_OGL`.

Anyway my question is: can you recommend a best practice for these kind of special cases, or can You imagine this issue to be solved in the kinda near future?

- OS and version you are running (build: Windows 10, run: Android, device: Pocophone F1)
- Build tools and configuration you used to build the engine (Android Studio + CMake)

**Comment by TheMostDiligent** [comment]
Hello!
I think that one solution could be to update `CreateTextureFromGLHandle` method to take bind target along with the texture handle. This way you should be able to create external texture and then attach it Diligent texture object.

**Comment by adamikandras** [comment]
@TheMostDiligent But then I would still need to add that parameter to `Texture2D_OGL`, too, right?
Because that would still change the target with this line in the constructor `static_cast<GLenum>(TexDesc.SampleCount > 1 ? GL_TEXTURE_2D_MULTISAMPLE : GL_TEXTURE_2D)`.

**Comment by TheMostDiligent** [comment]
Yes, there will be some changes: `Texture2D_OGL` and its friends define the target based on texture type. When non-null target is given to `CreateTextureFromGLHandle`, they should use it instead.

**Comment by adamikandras** [comment]
@TheMostDiligent I've tried to make it work, but it seems like these kind of textures don't provide the width attribute (at least its 0 when queried) and other types of auto checks fail inside Diligent (`GetTextureDescFromGLHandle` and its friends), too. These checks are cool, but for this use case they make it very difficult to integrate this target into the system this way. I would say it requires some other approach. I couldn't even get to the point when these textures need a special sampler in the shaders: `uniform samplerExternalOES sTexture;`, which would be another interesting journey.
I understand if it could be a low prio thing now from the engine point of view, but I would be happy to see it in the future. Sadly I don't have the time now to try to implement it in a mergable way for You.
Thanks for the help anyway. :)

**Comment by adamikandras** [comment]
What do You think is there a way to embed some raw GLES code for this in my engine, so it won't conflict with Diligent's internal state and the overall context?

**Comment by TheMostDiligent** [comment]
@adamikandras There were indeed quite a few more things that needed to be fixed, however everything works fine now. In fact, I added a [new sample](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Android/HelloAR) that uses Diligent in a simple Android AR application.

![Screenshot](https://user-images.githubusercontent.com/61806567/81882159-d7439000-9546-11ea-9921-518a0ffc0474.png)

**Comment by adamikandras** [comment]
@TheMostDiligent
OMG
That's awesome!!
I wouldn't dream about having this working anytime soon.
That's what I call the best community management!
Thanks a lot!

**Comment by TheMostDiligent** [comment]
I am trying to find good use cases for the engine and AR sounded like a very good one. Also, it initially seemed to be an easy thing to do, but I always keep discounting that things are never easy on Android, and it doesn't lack annoying issues to discover.
Anyway, it seems to be working fine now and hopefully it will be useful.
