### ISSUE TITLE
Add suport for creating swapchain directly from GLFW window.

### ISSUE THREAD

**Issue by markusgod** [DiligentGraphics/DiligentCore#141]
It would be nice to have possibility to do something like this: 
```
pFactoryVk->CreateSwapChainVk(pDevice, pImmediateContext, SCDesc, GLFWwindow, &pSwapChain);
```

**Comment by TheMostDiligent** [comment]
The library provides tools to create the swap chain from native window handle for all platforms. If it is possible to get this handle from GLFW or any other window library, it is straightforward to create the swap chain.
Extracting this handle inside the library, and adding extra dependency for that reason, does not seem to be reasonable.
