### ISSUE TITLE
Support for HLSL Shader Model 6 in DX12

### ISSUE THREAD

**Issue by PArcos** [DiligentGraphics/DiligentCore#143]
Hi,
Are there plans to support the newest features such as HLSL 6 wave intrinsics? I understand this would imply switching to the newest shader compiler toolchain (DXC).

Thanks for your great work!

**Comment by TheMostDiligent** [comment]
Hi!
Yes I am planning to switch to DXC in D3D12 backend.

**Comment by TheMostDiligent** [comment]
This is now enabled in the latest version: DXC can be used to compile HLSL in D3D12 and Vulkan backends
