### ISSUE TITLE
Support visual studio graphics debugger in D3D12 backend.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#153]
This is just a nice-to-have suggestion.

Currently it seems d3d11 backend works fine in visual studio graphics debugger, while d3d12 backend will cause the visual studio graphics debugger stop working and sometimes crash (by infinite recursion?). It would be nice to get it also working.

**Comment by TheMostDiligent** [comment]
If VS graphics debugger crash, it does not seem like a Diligent bug.

**Comment by crlf0710** [comment]
Maybe it's not a bug at all... i'm not certain. [This web page](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/walkthrough-capturing-graphics-information-programmatically?view=vs-2019) says that `IDXGraphicsAnalysis` should be used when rendering to a texture, and indeed i am since i'm using MSAA, so it'll be nice anyway if Diligent Engine can gain support for `IDXGraphicsAnalysis` somehow... 

I'm quite a beginner though so take my words with a grain of salt =)

**Comment by TheMostDiligent** [comment]
If your goal is to capture, debug and analyze the frame it is much easier to use special tools such as [renderdoc](https://renderdoc.org/). Programmatically capturing the frame would be a big hassle.

**Comment by TheMostDiligent** [comment]
Closing this issue. Feel free to ask questions on gitter/discord or open a new issue.
