### ISSUE TITLE
Code miscompilation on MSVC 15.6.7 version release build

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#159]
We found that there's code miscompilation with the release build of MSVC 15.6.7.
Code like these [here](https://github.com/DiligentGraphics/DiligentCore/blob/master/Common/interface/BasicMath.hpp#L236-L237) can be optimized and side effects are not properly observed when the second (*it++), leading the result being a simple repetition of the first element:
```c++
    template <typename Y>
    static Vector2 MakeVector(Y it)
    {
        return Vector2{static_cast<T>(*it++),
                       static_cast<T>(*it++)};
    }
```
According to [cppreference](https://en.cppreference.com/w/cpp/language/eval_order) clause 10, C++11 standard has specified order, and  i think it's the compiler's fault in this case. However it would be nice to give some warnings in documentation or code, or workaround this issue entirely.

**Comment by TheMostDiligent** [comment]
Hi! Can you post a simple code snippet that reproduces the problem?

**Comment by crlf0710** [comment]
Indeed! here's a code snippet:
```c++
#include <stdio.h>

template <typename T>
struct Vector2 {
	Vector2(T _x, T _y) {
		x = _x;
		y = _y;
	}
	T x;
	T y;

	template <typename Y>
	static Vector2 MakeVector(Y it)
	{
		return Vector2{ static_cast<T>(*it++),
			static_cast<T>(*it++) };
	}
};

static float values[2] = { 1.0f, 2.0f };

int main()
{
	auto v = Vector2<float>::MakeVector(values);
	printf("%lf\n", v.y);
	
    return 0;
}
```
With MSVC 15.6.7 release build, the output is 1.0. (unexpected)
With MSVC 15.6.7 debug build, the output is 2.0. (intended)
With MSVC 16.x the output is always 2.0. (intended)

**Comment by TheMostDiligent** [comment]
Thanks, this is very interesting! I actually now think that this may be an UB because the order of argument evaluation is not specified. So MSVC might not be wrong. Will fix this.

**Comment by crlf0710** [comment]
It is specified after C++11.  But it would be nice to avoid triggering this bug at all anyway. Thanks a lot.
