### ISSUE TITLE
[suggestion] Change data structs to aggregates (in C++20)

### ISSUE THREAD

**Issue by hnOsmium0001** [DiligentGraphics/DiligentCore#164]
Currently when compiling with C++, most data structs (XxxCreateInfo, XxxDesc, vectors, rects/boxes, etc.) provide a constructor with all members as parameters. This may be desirable, but since C++20 introduced designated initializers, the ctors prevent this usage:
```cpp
SwapChainDesc desc{
    .IsPrimary = true,
    .Width = xxx,
    .Height = yyy,
};
```

I think it would be very benefitial to add a preprocessor to disable the ctors in C++20.

Alternatively removing them should work, as the compiler is going to provide a per-member constructor for aggregates anyways (applies for all post-C++11 versions).
https://en.cppreference.com/w/cpp/language/aggregate_initialization

**Comment by TheMostDiligent** [comment]
What happens if somebody doesn't use (forget to/don't know about) designated initializers and writes code like this:

```cpp
SwapChainDesc desc;
desc.Width = 1280;
desc.Height = 1024;
desc.ColorBufferFormat = TEX_FORMAT_RGBA8_UNORM_SRGB;
desc.DepthBufferFormat = TEX_FORMAT_D32_FLOAT;
desc.BufferCount = 2;
pFactory->CreateSwapChain(&desc, ...);
```

**Comment by TheMostDiligent** [comment]
Or you mean just remove the ctors, but not default initializers?

**Comment by hnOsmium0001** [comment]
Just the ctors, not the default initializers, as the standards allow them past C++14.
> no default member initializers | (since C++11) (until C++14)

So keep all default initializers, and only provide the ctor if version <= C++11.
If you don't mind, I can submit a PR to do this, but it might be after a few weeks.

**Comment by MikhailGorobets** [comment]
Perhaps the best solution is to do as in vulkan.hpp. There is an  `VULKAN_HPP_NO_STRUCT_CONSTRUCTORS` macro used for this.

**Comment by TheMostDiligent** [comment]
Some structs (e.g. `LayoutElement`) have overloaded constructors. Removing them will break existing code. I would also argue if 

```cpp
LayoutElement{
  .InputIndex = 1,
  .BufferSlot = 0, 
  .NumComponents = 3,
  .ValueType = VT_FLOAT32
};
```
is going to be better than

```cpp
LayoutElement{1, 0, 3, VT_FLOAT32}
```

You will be able to do

```cpp
LayoutElement{nullptr, 1, 0, 3, VT_FLOAT32}
```
but, `nullptr` will be required as `HLSLSemantic` is the first member of the struct.

Moreover, client code will need to be compiled with different preprocessor settings than core modules, which may cause some problems.

So I honestly think it is not worth it. In the end, 

```cpp
SwapChainDesc desc;
desc.IsPrimary = true;
desc.Width = xxx;
desc.Height = yyy;
```

even saves one line of code.
