### ISSUE TITLE
Add D3D11_RESOURCE_MISC_SHARED option to share texture 

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#179]
(Click "Preview" to turn any URL into a clickable link)

If you have build or run problems, please read [troubleshooting](https://github.com/DiligentGraphics/DiligentEngine/blob/master/Troubleshooting.md) first.

Please double-check that your [code is up-to-date, including all submodules](https://github.com/DiligentGraphics/DiligentEngine#cloning-the-repository).

If you have a question that does not require creating an issue, you may ask it on [gitter](https://gitter.im/diligent-engine/Lobby).

For performance issues, please make sure you are running release builds. Debug builds may be significantly slower, especially on Windows.

For GPU-related problems, please make sure you have up-to-date drivers.

Please provide the following information:

- OS and version you are running (e.g. Windows 10.0.18362, MacOS Catalina 10.15, etc.)
- Build tools and configuration you used to build the engine (e.g. Visual Studio 2017 Debug x64 + CMake 3.15.4)
- GPU and driver version you have installed on your system
- Debug output, especially messages from Diligent
- Call stack (if available)
- If you experience a problem with one back-end, please try running other back-ends and see if the same issue arises

**Comment by TheMostDiligent** [comment]
How are you planning to use the flag? Diligent currently does not support multiple devices, so the flag will not be useful. Besides, D3D11 documentations says that only 2D non-mipmapped textures can be shared which limits the usability even further.
If you need to create a shared D3D11 texture, you can create it using D3D11 device, and then attach Diligent texture to existing resources.

**Comment by olegviz** [comment]
What about sharing resources between 2 applications ? For example one
application create this shared render target texture and second application
rendering to this external source .
Both of them using dx11 device .

 Ok , i can create this native dx11 texture and attach it to diligent as
you suggest .
Dx12 and vulkan do not have this flag ?

**Comment by olegviz** [comment]
GetSharedHandle and OpenSharedHandle used for this
Shared texture access .

**Comment by TheMostDiligent** [comment]
Closing this for now. Multi GPU and resource sharing will require a different approach and `D3D11_RESOURCE_MISC_SHARED` flag is a D3D11-exclusive and very specific feature. It has not counterparts in other backends.
