### ISSUE TITLE
Vulkan V-Sync

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentCore#181]
Hello, Egor. Is there a way to disable V-Sync in the Vulkan backend? 
I checked the code there is not used VK_PRESENT_MODE_IMMEDIATE_KHR.
AMD GPUs  dont't have VK_PRESENT_MODE_MAILBOX_KHR, and therefore in function
` void SwapChainVkImpl::CreateVulkanSwapChain()`  VK_PRESENT_MODE_FIFO_KHR will always be choosed

**Comment by TheMostDiligent** [comment]
`VK_PRESENT_MODE_IMMEDIATE_KHR` is not used because it results in tearing. If `VK_PRESENT_MODE_MAILBOX_KHR` is not available, then VSync can't be disabled in current implementation.

**Comment by MikhailGorobets** [comment]
> `VK_PRESENT_MODE_IMMEDIATE_KHR` is not used because it results in tearing. If `VK_PRESENT_MODE_MAILBOX_KHR` is not available, then VSync can't be disabled in current implementation.

`VK_PRESENT_MODE_FIFO_KHR` brings problems. Let the screen refresh rate be 60Hz and we use double buffering. If the frame isn't rendered in 16.7 ms, then it waits for the next synchronization tick. That is, the frame on the screen will remain at 33.4ms. This is partially solved by triple buffering. Also we have input lag, when use V-Sync, which is critical for FPS games. And I think when we use `VK_PRESENT_MODE_IMMEDIATE_KHR` we will ​​get Free-Sync working(But I'm not sure).

**Comment by TheMostDiligent** [comment]
`VK_PRESENT_MODE_IMMEDIATE_KHR` immediately presents the contents of the buffer. There is no delay, but it may result in tearing as the presentation engine may switch to the next frame in the middle of presentation.

**Comment by MikhailGorobets** [comment]
I just mean when we call `pSwapChain->Present (0)`, we probably want to get the minimum latency, but there is a possibility of frame tearing

**Comment by TheMostDiligent** [comment]
OK, I see.
I guess the swap chain my try to create `VK_PRESENT_MODE_MAILBOX_KHR` first, but if it is not available, it can resort to `VK_PRESENT_MODE_IMMEDIATE_KHR`

**Comment by MikhailGorobets** [comment]
Below is the pseudo code. I think this is the best way to do it. 
The earlier an element is added to `PreferredModes` the higher the priority
`
  std::vector<VkPresentModeKHR> SupportedModes = GetSupportedPresentModes(...)
  std::vector<VkPresentModeKHR> PreferredModes
  
  if (IsVSync) {
        PreferredModes.emplace_back(VK_PRESENT_MODE_FIFO_RELAXED_KHR)
        PreferredModes.emplace_back(VK_PRESENT_MODE_FIFO_KHR)
  } else {
        PreferredModes.emplace_back(VK_PRESENT_MODE_IMMEDIATE_KHR)
        PreferredModes.emplace_back(VK_PRESENT_MODE_MAILBOX_KHR)
        PreferredModes.emplace_back(VK_PRESENT_MODE_FIFO_KHR)
  }
  VkPresentModeKHR PresentMode = ChoosePresentModes(PreferredModes, SupportedModes);
`

**Comment by TheMostDiligent** [comment]
O only think that `VK_PRESENT_MODE_MAILBOX_KHR` should go before `VK_PRESENT_MODE_IMMEDIATE_KHR`

**Comment by MikhailGorobets** [comment]
> O only think that `VK_PRESENT_MODE_MAILBOX_KHR` should go before `VK_PRESENT_MODE_IMMEDIATE_KHR`

I don't know exactly which priority will be better in V-EZ Immediate samples higher than MAILBOX, and vice versa in Falcor

**Comment by MikhailGorobets** [comment]
> O only think that `VK_PRESENT_MODE_MAILBOX_KHR` should go before `VK_PRESENT_MODE_IMMEDIATE_KHR`
 
I don't know exactly which priority will be better. For example
- V-EZ
- - VK_PRESENT_MODE_IMMEDIATE_KHR
- - VK_PRESENT_MODE_MAILBOX_KHR

-  Falcor
- - VK_PRESENT_MODE_MAILBOX_KHR
- - VK_PRESENT_MODE_IMMEDIATE_KHR
