### ISSUE TITLE
Move GraphicsTools/interface/pch.h to corresponding include directory.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#187]
Hello, I'm using DiligentCore with a non-cmake build system. And i found that there's a `GraphicsTools/interface/pch.h` header which is easily picked up by another cpp file if that `interface` dir appears earlier than the module's own `include` directory. Would you mind creating a separate `include` directory for `GraphicsTools`? 

Thanks!

**Comment by TheMostDiligent** [comment]
`pch.h` in an interface directory is an oversight, will remove it.
