### ISSUE TITLE
DXC support on macOS

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#189]
I found that `#    error DXC is not supported on this platform` is triggered on macOS. However according to this: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/DxcOnUnix.rst it seems Dxc is also supported under macOS. Admittedly i haven't tried out DXC yet on macOS, just asking ahead: i wonder if there is any known issues with using that? (If there is, i guess i'll go HLSL2GLSL+glslang route. It's just that all my shaders are written in HLSL, so if DXC is used, it will save me one pass of conversion when using vulkan and i'll also get rid the glslang dependency.)

By the way, it seems there's a small typo in filename of DXCompilerBaseLi**un**x.hpp in the repo.

**Comment by TheMostDiligent** [comment]
We found that DXC is still not at the same level of maturity as legacy D3D compiler or glslang. We've seen quite a few cases where shaders compiled with DXC did not work as expected, though it is certainly getting better with every release.
We use DXC to compile shaders that require SM6.0+ (mesh shaders, ray tracing). Nothing of this functionality is supported on MacOS anyway, so we did not prioritize enabling DXC on Mac as glslang fully covers everything that MacOS supports. Enabling DXC on Mac will likely not a big problem though.
If you don't want to use glslang, you can compile HLSL with DXC and then use SPIRV bytecode directly.

**Comment by crlf0710** [comment]
Thanks! 👍

**Comment by TheMostDiligent** [comment]
> HLSL2GLSL+glslang route

Just FYI, glslang can compile HLSL directly, there is no need to convert it to GLSL first. HLSL2GLSL is only used for OpenGL/GLES backends. The only issue with glslang is that it only supports up to SM5.1, and it seems they are not planning to add 6.0 features, so far at least.
