### ISSUE TITLE
HLSL2GLSL geometry shader `SV_PrimitiveID` support.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#194]
Hi, i've recently found a small issue in HLSL2GLSL conversion.

The code [here](https://github.com/DiligentGraphics/DiligentCore/blob/4454515263e2f1ddd3508813403e54f9fe084403/Graphics/HLSL2GLSLConverterLib/src/HLSL2GLSLConverterImpl.cpp#L3523-L3527) assumes the geometry shader arguments consists only of one input and one output. However in my geometry shader, there's some hlsl semantic variables. Specially, i'm trying to use `SV_PrimitiveID` here. It would be nice if this bug can be fixed, thanks!

**Comment by TheMostDiligent** [comment]
Geometry shader can only have one input and one output, but it can be a struct where you can pack all required data. Please take a look at [Tutorial 07](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial07_GeometryShader).

**Comment by crlf0710** [comment]
@TheMostDiligent Hello, do you consider it a bug that FXC accepts additional semantic variables as input? Actually the code works fine under DX11 and DX12 backend. I didn't try out DXC status though.

I googled it and found that there's other examples that exhibit similar usage, like in [this tutorial](https://apprize.best/game/3d/12.html) 12.2.4 SV_PrimitiveID, the example code exhibit a similar usage:
```
[maxvertexcount(4)]

void GS(point VertexOut gin[1],

uint primID : SV_PrimitiveID,

inout TriangleStream<GeoOut> triStream)
```

I'm not sure whether `SV_PrimitiveID` can be included within the vertex struct because it's not part of the vertex buffer, it's generated by the pipeline instead... Maybe i can try it out.

If this is an expected limitation i can workaround this... though a little unfortunate.

**Comment by TheMostDiligent** [comment]
OK, it looks like there is indeed an issue with the converter: SV_PrimitiveId must be added as another input to GS function.

**Comment by crlf0710** [comment]
@TheMostDiligent any updates on this issue?
