### ISSUE TITLE
Add option to bind samplers by index

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#20]

**Comment by DiligentGraphics** [comment]
Closing this issue as now you can access individual samplers in the same way as other shader variables and bind sampler objects to them (435f70be7aebd9a669d6a276df67e8eb814a45e3, c2a6a2c4b716d45ddc92ed04bb0ac7fb7200e548, 1332922262631fb8d601f8636ae783b73e461cad). Binding sampler by HLSL register is D3D11-specific. This information can potentially be exposed from IShaderD3D11 object.
