### ISSUE TITLE
Compiler Error: Unknown Platform

### ISSUE THREAD

**Issue by DaOnlyOwner** [DiligentGraphics/DiligentCore#223]
Hello, sorry to bug you again, but I get a compiler error which I can't fix:

#error:  Unknown platform. Please define one of the following macros as 1:  PLATFORM_WIN32, PLATFORM_UNIVERSAL_WINDOWS, PLATFORM_ANDROID, PLATFORM_LINUX, PLATFORM_MACOS, PLATFORM_IOS.	

It actually happens when compiling a minimal example:
```
#include <Common/interface/RefCntAutoPtr.hpp>

int main()
{

}

```
- OS Version: Windows 10.0.19042
- Visual Studio 2019 Debug x64 + CMake 3.20.2
- RTX 2080, API Version: 1.2.142, Driver version: 457.120.0

**Comment by TheMostDiligent** [comment]
Please read [here](https://github.com/DiligentGraphics/DiligentEngine#integrating-diligent-engine-with-existing-build-system).
You may need to define one of the platform macros as the error suggests.

**Comment by DaOnlyOwner** [comment]
My CMakeLists looks more or less exactly like the example CMakeLists. So it is intended that the user of the library has to define platform macros?

**Comment by TheMostDiligent** [comment]
If in CMake you link your target with any of the backends, they will expose the required platform-specific macros. You can also look at [Tutorial00](https://github.com/DiligentGraphics/DiligentSamples/tree/master/Tutorials/Tutorial00_HelloWin32).

**Comment by DaOnlyOwner** [comment]
Ah so it is basically required to set the backends in the user CMake?

**Comment by TheMostDiligent** [comment]
https://github.com/DiligentGraphics/DiligentEngine#your-project-uses-cmake:

> Then the following steps need to be done:
> 
> Call add_subdirectory(DiligentCore)
> Add DiligentCore to the list of include directories
> Add dependencies on the targets implementing required rendering backends
>

**Comment by DaOnlyOwner** [comment]
Okay if I add the definitions mayself it works.

**Comment by TheMostDiligent** [comment]
Did you try to start with Tutorial00? It does not define the macros which are provided by Diligent targets.

**Comment by DaOnlyOwner** [comment]
Tutorial00 works for me. It's fine I just provide the definitions myself.
