### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#250]
I am currently creating a conan recipe for DiligentCore and it is extremely hard to do, as tagged versions of Diligent depend on the not-tagged versions of the Third-party libraries.

If we take for example spirv-headers:
https://github.com/bincrafters/conan-center-index/blob/main/recipes/spirv-headers/all/conandata.yml

Here we have the official releases from KhronosGroup repo.
Would it be possible for the next Diligent release to depend only on the tagged libraries?

**Comment by TheMostDiligent** [comment]
We had to make few minor changes to some of the third-party modules (SPIRV-Cross, in particular). Besides, [some modules](https://github.com/KhronosGroup/SPIRV-Tools/releases) don't have regular releases.
