### ISSUE TITLE
Disabling DIRECT3D11/12 does not have effect

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#254]
(Click "Preview" to turn any URL into a clickable link)
- OS Windows 10
- visualstudio2019buildtools installed with choco

I've run a command to build Diligent:
 cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64 -DDILIGENT_NO_DIRECT3D11=False -DDILIGENT_NO_DIRECT3D12=False
cd build\Win64
 cmake --build .  -j 6

log output:

Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Diligent-Primitives.vcxproj -> C:\sources\DiligentCore\build\Win64\Primitives\Debug\Diligent-Primitives.lib
  GenericCodeGen.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\glslang\Debug\GenericCodeGend.lib
  Validating DiligentCore module's source code formatting...
  OGLCompiler.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\OGLCompilersDLL\Debug\OGLCompilerd.l
  ib
  OSDependent.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\glslang\OSDependent\Windows\Debug\OS
  Dependentd.lib
  spirv-cross-core.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\SPIRV-Cross\Debug\spirv-cross-cored.lib
  glew-static.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glew\Debug\glew-static.lib
  MachineIndependent.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\glslang\Debug\MachineIndepend
  entd.lib
  glslang.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\glslang\Debug\glslangd.lib
  SPIRV-Tools-static.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\SPIRV-Tools\source\Debug\SPIRV-Tools.
  lib
  SPIRV-Tools-opt.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\SPIRV-Tools\source\opt\Debug\SPIRV-Tools
  -opt.lib
  SPIRV.vcxproj -> C:\sources\DiligentCore\build\Win64\ThirdParty\glslang\SPIRV\Debug\SPIRVd.lib
  clang-format validation passed: no issues found in 1084 files
  Diligent-BasicPlatform.vcxproj -> C:\sources\DiligentCore\build\Win64\Platforms\Basic\Debug\Diligent-BasicPlatform
  .lib
  Diligent-Win32Platform.vcxproj -> C:\sources\DiligentCore\build\Win64\Platforms\Win32\Debug\Diligent-Win32Platform
  .lib
  Diligent-Common.vcxproj -> C:\sources\DiligentCore\build\Win64\Common\Debug\Diligent-Common.lib
  Diligent-GraphicsAccessories.vcxproj -> C:\sources\DiligentCore\build\Win64\Graphics\GraphicsAccessories\Debug\Dil
  igent-GraphicsAccessories.lib
  Diligent-GraphicsEngine.vcxproj -> C:\sources\DiligentCore\build\Win64\Graphics\GraphicsEngine\Debug\Diligent-Grap
  hicsEngine.lib
  Diligent-GraphicsEngineNextGenBase.vcxproj -> C:\sources\DiligentCore\build\Win64\Graphics\GraphicsEngineNextGenBa
  se\Debug\Diligent-GraphicsEngineNextGenBase.lib
  Diligent-HLSL2GLSLConverterLib.vcxproj -> C:\sources\DiligentCore\build\Win64\Graphics\HLSL2GLSLConverterLib\Debug
  \Diligent-HLSL2GLSLConverterLib.lib
  DXBCUtils.cpp
C:\sources\DiligentCore\Graphics\ShaderTools\src\DXBCUtils.cpp(28,10): fatal error C1083: Cannot open include file:
'atlcomcli.h': No such file or directory [C:\sources\DiligentCore\build\Win64\Graphics\ShaderTools\Diligent-ShaderTo
ols.vcxproj]
  DXCompiler.cpp
C:\sources\DiligentCore\Graphics\ShaderTools\include\DXCompilerBaseWin32.hpp(30,10): fatal error C1083: Cannot open
include file: 'atlbase.h': No such file or directory [C:\sources\DiligentCore\build\Win64\Graphics\ShaderTools\Dilig
ent-ShaderTools.vcxproj]
  Generating Code...

**Comment by TheMostDiligent** [comment]
You should use `-DDILIGENT_NO_DIRECT3D11=TRUE -DDILIGENT_NO_DIRECT3D12=TRUE`

**Comment by AndreyMlashkin** [comment]
I have changed my build script, but I still get the same build error:

DEL build/Win64/CMakeCache.txt
cmake -S . -B ./build/Win64 -G "Visual Studio 16 2019" -A x64 -DDILIGENT_NO_DIRECT3D11=True -DDILIGENT_NO_DIRECT3D12=True
cd build\Win64
cmake --build . -j 6


C:\sources\DiligentCore\Graphics\ShaderTools\include\DXCompilerBaseWin32.hpp(30,10): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory [C:\sources\DiligentCore\build\Win64\Graphics\ShaderTools\Diligent-
ShaderTools.vcxproj]

**Comment by AndreyMlashkin** [comment]
Ah, I see, that it comes not from DIRECT3D11/12, but from DXC, sorry!

**Comment by TheMostDiligent** [comment]
https://github.com/DiligentGraphics/DiligentEngine#win32
You need to have ATL support enabled in Visual Studio.
