### ISSUE TITLE
Failed to build D3D12 backend with Clion

### ISSUE THREAD

**Issue by LeptusHe** [DiligentGraphics/DiligentCore#271]
When I used Clion to build D3D12 backend, it failed.
The compilers said that " fatal error C1083: can not open file: “GenerateMips/GenerateMipsLinearCS.h”: No such file or directory".

**Comment by TheMostDiligent** [comment]
https://github.com/DiligentGraphics/DiligentEngine/blob/master/Troubleshooting.md

CLion is not an officially supported build tool. Use Visual Studio.

**Comment by lectroMathew** [comment]
@TheMostDiligent Any plans on when we can get clean CMake support outside Visual Studio?
