### ISSUE TITLE
Add DX12 Agility support

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentCore#275]
https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/

**Comment by TheMostDiligent** [comment]
Agility parameters are set at [the application level](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/#2-set-agility-sdk-parameters) by exporting `D3D12SDKVersion` and `D3D12SDKPath` from the main .exe for the process.
It thus can't be implemented in GraphicsEngineD3D12.dll

**Comment by laurentcau** [comment]
I think defining D3D12SDKVersion and D3D12SDKPath is not the most difficult part. Each application can do it but if I'm not wrong, the Diligent code has to use the headers defined in the nuget, at least if DiligentEngine want to use new advanced features.

**Comment by TheMostDiligent** [comment]
At this point there are no features from the Agility SDK that Diligent needs to use. Run-time support of older platforms (e.g. to support mesh shaders on Windows versions that don't have it) does not require any changes on Diligent side.
