### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#276]
Could you please tag a new version. The latest tag is 4 months old.
It would be also great to tag all submodules to the same tag name, like glslang-v2.6.

**Comment by TheMostDiligent** [comment]
All versions are tagged
https://github.com/DiligentGraphics/DiligentCore/tags
Last tag is from 13 days ago.

**Comment by AndreyMlashkin** [comment]
Ou, great, thanks!
Could you please also tag the 3rd party libs?
Volk, glslang, SPIRV-* and Vulkan-Header

**Comment by TheMostDiligent** [comment]
We update third party modules infrequently, usually before releases. They are not related to the Diligent API version. Breaking changes do happen, but they are rare. 
You can find the third-party commits from the tagged Diligent Core commit versions.
