### ISSUE TITLE
CHECK macro collides with glog

### ISSUE THREAD

**Issue by logankaser** [DiligentGraphics/DiligentCore#335]
The popular C++ library [glog](https://github.com/google/glog) includes [macros for error checking](https://github.com/google/glog/blob/master/README.rst#check-macros) that unfortunately collide with the internal `CHECK` macro from diligent.
It's unclear to me if this is intended to be part of the public interface, but it would be nice if a solution could be found to use these libraries together.
This could be done by renaming `CHECK` to `DILIGENT_CHECK` for example.
Currently I solve this problem in my code base with a giant patch that renames `CHECK` to `DILIGENT_CHECK`,
but I thought it was worth bringing up in case others have run into this.

**Comment by TheMostDiligent** [comment]
Do you know which header leaks this macro?
Core interface headers should not be leaking it.

> Currently I solve this problem in my code base with a giant patch that renames CHECK to DILIGENT_CHECK,

There seem to only be 6 lines where this macro is actually used, so renaming it is possible

**Comment by logankaser** [comment]
Oh, you're right, turns out it was giant because I did not construct the regex correctly and it hit other macros in diligent like `CHECK_DEV` and `CHECK_*`
Thanks for renaming this!
