### ISSUE TITLE
DX12 UpdateBuffer() Allocation failure not handled.

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#349]
In DX12, UpdateBuffer() has an internal Allocate() call, and the CPUAddress is used as memcpy target without any nullptr checking.

**Comment by TheMostDiligent** [comment]
This is not the only place where nullptr is not cheked. If there is not enough dynamic space, there is no good way to recover from this error or for application to know about the error.

**Comment by crlf0710** [comment]
ok... maybe i should just close this then...
