### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#355]
there have been almost half a year and ~300 commits since the lat tag, could you please tag a new version of Diligent-core?

**Comment by TheMostDiligent** [comment]
We are finishing some updates. We will create a new tag in a couple of days to have them included.

**Comment by TheMostDiligent** [comment]
Added [API250014](https://github.com/DiligentGraphics/DiligentCore/tree/API250014) tag
