### ISSUE TITLE
Compiler Error C2440

### ISSUE THREAD

**Issue by lastmoonbeam** [DiligentGraphics/DiligentCore#37]
Hi! I was trying to build DiligentCore and got "Compiler Error C2440" in few places in code. 
'''
c:\diligentcore-master\primitives\interface\FormatString.h(68): error C2440: 'initializing': cannot convert from 'initializer list' to 'Diligent::MemorySizeFormatter<VkDeviceSize>'

C:\DiligentCore-master\Graphics\GraphicsEngineVulkan\src\VulkanUploadHeap.cpp(81): error C2440: 'initializing': cannot convert from 'initializer list' to 'Diligent::VulkanUploadHeap::UploadPageInfo'

'''

Only GL bakend was sucessfuly compiled all other are failed (
 
I'm use: VS2015, Win10, i7

**Comment by DiligentGraphics** [comment]
I will take a look, this is likely VS2015 issue. Meanwhile, do you have VS2017 to try?

**Comment by lastmoonbeam** [comment]
Thx! Now I've got VK bakend lib and dll, but for dx11/12 I going to download Win10SDK.
Nо, I don't have VS2017, I like vintage versions of VS even older then 2015 )

**Comment by DiligentGraphics** [comment]
Yes, you will need Win10SDK or you can generate solution that targets Win8.1 SDK:
cmake -D CMAKE_SYSTEM_VERSION=8.1 -H. -B./cmk_build/Win64 -G "Visual Studio 14 2015 Win64"
It will not support D3D12 backend though.

I understand that migration to new versions of Visual Studio may be cumbersome sometimes, but Microsoft does make improvements to it. The engine will not compile on VS 2012 as this version does not support all required c++ features.
