### ISSUE TITLE
'VERIFY' macro redefinition

### ISSUE THREAD

**Issue by SK83RJOSH** [DiligentGraphics/DiligentCore#371]
This is more of a sanitary issue than a bug, but DebugUtilities.hpp leaks `VERIFY` to anything relying on core in debug. This is usually fine of course, but my engine defines this as does the Windows SDK which can lead to some issues. What's the recommended course of action in this case? Disable DILIGENT_DEBUG or should this macro be renamed in core?

Personally I'd love for these kinds of macros prefixed or undefined once they're no longer in use; but that likely will be a breaking change so I figured I'd open this issue. 😄

**Comment by TheMostDiligent** [comment]
DebugUtilities.hpp file does not leak the macro, but is the file that defines it. It is supposed to be an internal macro and should not generally leak outside.
Do you know through which header `VERIFY` leaks?

**Comment by SK83RJOSH** [comment]
> DebugUtilities.hpp file does not leak the macro, but is the file that defines it. It is supposed to be an internal macro and should not generally leak outside. Do you know through which header `VERIFY` leaks?

Aha, sorry about that I should have figured. It's being leaked by RefCntAutoPtr.hpp, by one of it's includes, Cast.hpp; I assume this is intended to be used by the end user since it's used rather heavily in examples? :)

**Comment by TheMostDiligent** [comment]
Yes, `RefCntAutoPtr.hpp` should probably not leak the macro - will take a look how to fix this.

**Comment by TheMostDiligent** [comment]
So it looks like it is not that easy to remove this macros. I would probably suggest to `#undef VERIFY` after including the header. Not ideal, but should fix the problem.

**Comment by SK83RJOSH** [comment]
That was my workaround for now, so no worries. Thanks for taking a look 🙂
