### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#375]
It  is already a while passed since the last tag was created (2 Months to be precise). Could you please create a new tag? 2.5.3

**Comment by TheMostDiligent** [comment]
Yes, there will be a new tag soon.

**Comment by AndreyMlashkin** [comment]
Is there any ETA?

**Comment by TheMostDiligent** [comment]
Likely this week.
Note that we add tags when there is a reasonable milestone.

**Comment by TheMostDiligent** [comment]
Added tag [API252003](https://github.com/DiligentGraphics/DiligentCore/releases/tag/API252003)
