### ISSUE TITLE
nointerpolation not available with OpenGL

### ISSUE THREAD

**Issue by JD31** [DiligentGraphics/DiligentCore#376]
I need to communicate between vertex and fragment shader a non interpolated variable.
In OpenGL it is achievable and it is also in DirectX with 'nointerpolation' keyword.
I expected the HLSL -> GLSL converter to adapt the shader code, but it generates an error:

```
Diligent Engine: ERROR in Diligent::HLSL2GLSLConverterImpl::ConversionStream::ParseShaderParameter() (HLSL2GLSLConverterImpl.cpp, 2234): Missing argument type
>  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >

    float4 Pos  : SV_POSITION;
    float3 Norm : NORMAL;    // world-space normal
    nointerpolation uint BackFace : MATERIAL;
    ^
};
<  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <
```

**Comment by TheMostDiligent** [comment]
Will take a look, though for a uint argument, nointerpolation is not needed. It is automatically nointerpolation
