### ISSUE TITLE
package HLSL2GLSLConverterImpl.hpp

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#381]
This file is not marked as a public interface and therefore not installed:
Graphics/HLSL2GLSLConverterLib/include/HLSL2GLSLConverterImpl.hpp

Nevertheless, diligent-tools includes this file in HLSL2GLSLConverter/src/HLSL2GLSLConverterApp.cpp
Could you please also add HLSL2GLSLConverterImpl.hpp to install targets or even better to separate HLSL2GLSLConverter to a new repository

**Comment by AndreyMlashkin** [comment]
Thanks a log for a very quick fix!
It would be really great it you also tag current core and tools versions, I could then release a new conan version of diligent.

**Comment by AndreyMlashkin** [comment]
19: option to disable all tests would spare this patch, yes
20: yes, cmake fails, if no file exists. Conan does not checkout submodules, so there is no file there. A check, if file exists would help. I am not sure, if there is a possibility to ignore an error, if no file is there in install() command
21: Hmmm, yes, that would spare a patch and I will try it
22: try to remove glslang in this line in the main CMakeLists.txt:
"set_directory_root_folder("glslang" "DiligentCore/ThirdParty/glslang")"
23: thanks for the hint, I will try
24: yes
25: I will try. I don't yet know, if /W4 ... /W0 is a correct flags combination after all

**Comment by AndreyMlashkin** [comment]
It's not defined in a recipe. But grepping through the project shows, that is it defined in cmake:

ThirdParty/CMakeLists.txt:        set(SPIRV_CROSS_ENABLE_HLSL OFF CACHE BOOL "Enable HLSL target support.")
Graphics/ShaderTools/CMakeLists.txt:set(ENABLE_HLSL FALSE)
Graphics/ShaderTools/CMakeLists.txt:    set(ENABLE_HLSL TRUE)
Graphics/ShaderTools/CMakeLists.txt:if(ENABLE_HLSL)
Graphics/ShaderTools/src/GLSLangUtils.cpp:#    define ENABLE_HLSL

**Comment by AndreyMlashkin** [comment]
If I remove install patch, it fails here:

Install the project...
-- Install configuration: "Debug"
-- Installing: /home/andrei/.conan/data/diligent-core/api.252003/andrei/test/package/6881f80c17218d135fdf22c03d23b300c1292b03/lib/source_subfolder/Debug/libDiligentCore.a
-- Installing: /home/andrei/.conan/data/diligent-core/api.252003/andrei/test/package/6881f80c17218d135fdf22c03d23b300c1292b03/Licenses/DiligentEngine-License.txt
-- Installing: /home/andrei/.conan/data/diligent-core/api.252003/andrei/test/package/6881f80c17218d135fdf22c03d23b300c1292b03/lib/source_subfolder/Debug/libglew-static.a
-- Installing: /home/andrei/.conan/data/diligent-core/api.252003/andrei/test/package/6881f80c17218d135fdf22c03d23b300c1292b03/Licenses/ThirdParty/source_subfolder/GLEW-License.txt
CMake Error at source_subfolder/ThirdParty/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/home/andrei/.conan/data/diligent-core/api.252003/andrei/test/build/6881f80c17218d135fdf22c03d23b300c1292b03/source_subfolder/ThirdParty/SPIRV-Headers/LICENSE":
  No such file or directory.
Call Stack (most recent call first):
  source_subfolder/cmake_install.cmake:55 (include)
  cmake_install.cmake:47 (include)

**Comment by AndreyMlashkin** [comment]
How is then cmake variable forwarded to C++ code?

**Comment by TheMostDiligent** [comment]
It is not forwarded. It is named the same, but it only defines the logic of CMake

**Comment by AndreyMlashkin** [comment]
0021 relates to https://github.com/conan-io/conan-center-index/pull/11702

**Comment by AndreyMlashkin** [comment]
I have also added an override for compilation options in here
https://github.com/conan-io/conan-center-index/pull/11702/commits/9cb21aa04fc601ffe3af4e8214669e01a45559d9

**Comment by TheMostDiligent** [comment]
> If I remove install patch, it fails here:

Try to define backwards alias in the master CMake:

```
add_library(SPIRV-Headers ALIAS SPIRV::Headers)
```

If this does not work, can you comment out license installation commands one-by-one to see which ones exactly fail?

**Comment by TheMostDiligent** [comment]
> I have also added an override for compilation options in here

Like I said, there is no need to override `/W4` with `/W0`. You need to remove `/WX`, which can be done by setting `DILIGENT_MSVC_COMPILE_OPTIONS` to empty string like you do with `DILIGENT_CLANG_COMPILE_OPTIONS`

**Comment by AndreyMlashkin** [comment]
> > If I remove install patch, it fails here:
> 
> Try to define backwards alias in the master CMake:
> 
> ```
> add_library(SPIRV-Headers ALIAS SPIRV::Headers)
> ```
> 
> If this does not work, can you comment out license installation commands one-by-one to see which ones exactly fail?

Yes, that worked, I have removed two more patches

**Comment by AndreyMlashkin** [comment]
Could you please produce a new tag? I will create a new conan packages. For me it is important to add HLSL2GLSLConverterImpl to diligent-tools. Currently, it's not built with conan

**Comment by TheMostDiligent** [comment]
> Yes, that worked, I have removed two more patches

👍


As to 22: `glslang::glslang` target imported from the package and `glslang` defined by CMake directly use different public include directories, which is incorrect. I would suggest fixing it by defining the interface `glslang` library instead of ALIAS in the master CMake:

```CMake
add_library(glslang INTERFACE)
target_link_libraries(glslang INTERFACE glslang::glslang)
target_include_directories(glslang INTERFACE path/to/glslang/glslang)
```

> Could you please produce a new tag?

Yes, let's figure out the remaining issues with patches. I think we are left with 22 and 19. And also I still don't understand why `ENABLE_HLSL` gets redefined.

**Comment by AndreyMlashkin** [comment]
I have found, where is this definition comes from:
            self.cpp_info.components["glslang-core"].defines.append("ENABLE_HLSL")

https://github.com/conan-io/conan-center-index/blob/3fa917aed5d0687cf9c0aacf0e4c2482911c10a4/recipes/glslang/all/conanfile.py#L227

it adds a define to C++ code "from console"

**Comment by AndreyMlashkin** [comment]
So, my version from PR contains only two patches:
0019-252003-exclude-tests.patch
0023-252003-fix-warning-as-error.patch

As I see, there should be some work to be done in diligent:
- adding a flag, disabling all tests
- Werror should be a default value of DILIGENT_CLANG_COMPILE_OPTIONS

**Comment by TheMostDiligent** [comment]
As to 0019, what error do you get if you add Tests directory? If there is no `gtest` target, it should do nothing

**Comment by AndreyMlashkin** [comment]
I have tried it locally, it works. You can apply this patch and check on your own:

diff --git a/recipes/diligent-core/all/conandata.yml b/recipes/diligent-core/all/conandata.yml
index 1c398ce59..990f0da52 100644
--- a/recipes/diligent-core/all/conandata.yml
+++ b/recipes/diligent-core/all/conandata.yml
@@ -1,4 +1,7 @@
 sources:
+  "cci.20220718":
+    url: "https://github.com/DiligentGraphics/DiligentCore/archive/43ae908b68c3fe140e0caebd02b7bf04311c211e.zip"
+    sha256: "f69d09f5ec0e7cf95b8cc0224552df0badbf45b873a9dcbd7f4fa4f9ff41034c"

Could you please create a tag then? From now on, it should be very easy to do

**Comment by AndreyMlashkin** [comment]
Producing a new conan version from current diligent-core master

**Comment by TheMostDiligent** [comment]
So no patches needed now?

**Comment by AndreyMlashkin** [comment]
For current master no patches needed. Once you create a new tag, I will start a PR, creating a new conan version :)

**Comment by TheMostDiligent** [comment]
👍
Will add a new tag to [this commit](https://github.com/DiligentGraphics/DiligentCore/commit/11708dcfad63adfb35419bf095d29a6e7130d33e).

**Comment by TheMostDiligent** [comment]
Added tag [API252004](https://github.com/DiligentGraphics/DiligentCore/releases/tag/API252004)
