### ISSUE TITLE
Why API252004 tag was changed?

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentCore#384]
Recently a file associated with API252004 tag archive was changed. What was the reason?
relates to https://github.com/conan-io/conan-center-index/pull/12255

**Comment by TheMostDiligent** [comment]
I believe there were some changes that needed to be tagged - can't remember the exact reason now

**Comment by TheMostDiligent** [comment]
FYI, for questions that are not really issues, you can use the [discussions](https://github.com/DiligentGraphics/DiligentCore/discussions). Also, there is a [discord channel](https://discord.gg/t7HGBK7).
