### ISSUE TITLE
VK Error Code: ERROR_OUT_OF_DEVICE_MEMORY

### ISSUE THREAD

**Issue by IngoChow** [DiligentGraphics/DiligentCore#398]
Failed to call pFactoryVk->CreateSwapChainVk(m_pDevice, m_pImmediateContext, SCDesc, window, &m_pSwapChain).
It works on D3D11 & D3D12.
Thanks.

Diligent Engine: Info: GPU dynamic heap created. Total buffer size: 8.00 MB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (16.00 MB, type idx: 1). Current allocated size: 16.00 MB
Diligent Engine: Info: Requested color buffer format TEX_FORMAT_RGBA8_UNORM_SRGB is not supported by the surface and will be replaced with TEX_FORMAT_BGRA8_UNORM_SRGB
Diligent Engine: Info: Using SURFACE_TRANSFORM_IDENTITY swap chain pretransform
Diligent Engine: Info: Using VK_PRESENT_MODE_FIFO_RELAXED_KHR swap chain present mode
Diligent Engine: ERROR in Diligent::SwapChainVkImpl::CreateVulkanSwapChain() (SwapChainVkImpl.cpp, 473): Failed to create Vulkan swapchain
VK Error Code: ERROR_OUT_OF_DEVICE_MEMORY
Diligent Engine: ERROR in Diligent::`anonymous-namespace'::EngineFactoryVkImpl::CreateSwapChainVk() (EngineFactoryVk.cpp, 1376): Failed to create the swap chain
Debug expression failed:
m_pSwapChain != nullptr

- Windows 10.0.19044
- Visual Studio 2019 Debug x64 + CMake 3.24.2)

**Comment by TheMostDiligent** [comment]
What GPU are you using?
Are your drivers up-to-date?

**Comment by IngoChow** [comment]
My GPU is NVIDIA GeForce RTX 2080.
My driver is the latest driver.

Thanks.

Diligent Engine: Info: Using physical device 'NVIDIA GeForce RTX 2080', API version 1.3.224, Driver version 16.8.0.
Diligent Engine: Info: Extensions supported by device 'NVIDIA GeForce RTX 2080': 
    VK_KHR_16bit_storage 0.0.1                         VK_KHR_8bit_storage 0.0.1                            VK_KHR_acceleration_structure 0.0.13
    VK_KHR_bind_memory2 0.0.1                          VK_KHR_buffer_device_address 0.0.1                   VK_KHR_copy_commands2 0.0.1
    VK_KHR_create_renderpass2 0.0.1                    VK_KHR_dedicated_allocation 0.0.3                    VK_KHR_deferred_host_operations 0.0.4
    VK_KHR_depth_stencil_resolve 0.0.1                 VK_KHR_descriptor_update_template 0.0.1              VK_KHR_device_group 0.0.4
    VK_KHR_draw_indirect_count 0.0.1                   VK_KHR_driver_properties 0.0.1                       VK_KHR_dynamic_rendering 0.0.1
    VK_KHR_external_fence 0.0.1                        VK_KHR_external_fence_win32 0.0.1                    VK_KHR_external_memory 0.0.1
    VK_KHR_external_memory_win32 0.0.1                 VK_KHR_external_semaphore 0.0.1                      VK_KHR_external_semaphore_win32 0.0.1
    VK_KHR_format_feature_flags2 0.0.1                 VK_KHR_fragment_shader_barycentric 0.0.1             VK_KHR_fragment_shading_rate 0.0.2
    VK_KHR_get_memory_requirements2 0.0.1              VK_KHR_image_format_list 0.0.1                       VK_KHR_imageless_framebuffer 0.0.1
    VK_KHR_maintenance1 0.0.2                          VK_KHR_maintenance2 0.0.1                            VK_KHR_maintenance3 0.0.1
    VK_KHR_maintenance4 0.0.2                          VK_KHR_multiview 0.0.1                               VK_KHR_pipeline_executable_properties 0.0.1
    VK_KHR_pipeline_library 0.0.1                      VK_KHR_present_id 0.0.1                              VK_KHR_present_wait 0.0.1
    VK_KHR_push_descriptor 0.0.2                       VK_KHR_ray_query 0.0.1                               VK_KHR_ray_tracing_maintenance1 0.0.1
    VK_KHR_ray_tracing_pipeline 0.0.1                  VK_KHR_relaxed_block_layout 0.0.1                    VK_KHR_sampler_mirror_clamp_to_edge 0.0.3
    VK_KHR_sampler_ycbcr_conversion 0.0.14             VK_KHR_separate_depth_stencil_layouts 0.0.1          VK_KHR_shader_atomic_int64 0.0.1
    VK_KHR_shader_clock 0.0.1                          VK_KHR_shader_draw_parameters 0.0.1                  VK_KHR_shader_float16_int8 0.0.1
    VK_KHR_shader_float_controls 0.0.4                 VK_KHR_shader_integer_dot_product 0.0.1              VK_KHR_shader_non_semantic_info 0.0.1
    VK_KHR_shader_subgroup_extended_types 0.0.1        VK_KHR_shader_subgroup_uniform_control_flow 0.0.1    VK_KHR_shader_terminate_invocation 0.0.1
    VK_KHR_spirv_1_4 0.0.1                             VK_KHR_storage_buffer_storage_class 0.0.1            VK_KHR_swapchain 0.0.70
    VK_KHR_swapchain_mutable_format 0.0.1              VK_KHR_synchronization2 0.0.1                        VK_KHR_timeline_semaphore 0.0.2
    VK_KHR_uniform_buffer_standard_layout 0.0.1        VK_KHR_variable_pointers 0.0.1                       VK_KHR_vulkan_memory_model 0.0.3
    VK_KHR_win32_keyed_mutex 0.0.1                     VK_KHR_workgroup_memory_explicit_layout 0.0.1        VK_KHR_zero_initialize_workgroup_memory 0.0.1
    VK_EXT_4444_formats 0.0.1                          VK_EXT_attachment_feedback_loop_layout 0.0.2         VK_EXT_blend_operation_advanced 0.0.2
    VK_EXT_border_color_swizzle 0.0.1                  VK_EXT_buffer_device_address 0.0.2                   VK_EXT_calibrated_timestamps 0.0.2
    VK_EXT_color_write_enable 0.0.1                    VK_EXT_conditional_rendering 0.0.2                   VK_EXT_conservative_rasterization 0.0.1
    VK_EXT_custom_border_color 0.0.12                  VK_EXT_depth_clip_control 0.0.1                      VK_EXT_depth_clip_enable 0.0.1
    VK_EXT_depth_range_unrestricted 0.0.1              VK_EXT_descriptor_indexing 0.0.2                     VK_EXT_discard_rectangles 0.0.1
    VK_EXT_extended_dynamic_state 0.0.1                VK_EXT_extended_dynamic_state2 0.0.1                 VK_EXT_external_memory_host 0.0.1
    VK_EXT_fragment_shader_interlock 0.0.1             VK_EXT_full_screen_exclusive 0.0.4                   VK_EXT_graphics_pipeline_library 0.0.1
    VK_EXT_hdr_metadata 0.0.2                          VK_EXT_host_query_reset 0.0.1                        VK_EXT_image_2d_view_of_3d 0.0.1
    VK_EXT_image_robustness 0.0.1                      VK_EXT_image_view_min_lod 0.0.1                      VK_EXT_index_type_uint8 0.0.1
    VK_EXT_inline_uniform_block 0.0.1                  VK_EXT_line_rasterization 0.0.1                      VK_EXT_load_store_op_none 0.0.1
    VK_EXT_memory_budget 0.0.1                         VK_EXT_memory_priority 0.0.1                         VK_EXT_mesh_shader 0.0.1
    VK_EXT_multi_draw 0.0.1                            VK_EXT_mutable_descriptor_type 0.0.1                 VK_EXT_non_seamless_cube_map 0.0.1
    VK_EXT_opacity_micromap 0.0.2                      VK_EXT_pageable_device_local_memory 0.0.1            VK_EXT_pci_bus_info 0.0.2
    VK_EXT_pipeline_creation_cache_control 0.0.3       VK_EXT_pipeline_creation_feedback 0.0.1              VK_EXT_pipeline_robustness 0.0.1
    VK_EXT_post_depth_coverage 0.0.1                   VK_EXT_primitive_topology_list_restart 0.0.1         VK_EXT_primitives_generated_query 0.0.1
    VK_EXT_private_data 0.0.1                          VK_EXT_provoking_vertex 0.0.1                        VK_EXT_queue_family_foreign 0.0.1
    VK_EXT_robustness2 0.0.1                           VK_EXT_sample_locations 0.0.1                        VK_EXT_sampler_filter_minmax 0.0.2
    VK_EXT_scalar_block_layout 0.0.1                   VK_EXT_separate_stencil_usage 0.0.1                  VK_EXT_shader_atomic_float 0.0.1
    VK_EXT_shader_demote_to_helper_invocation 0.0.1    VK_EXT_shader_image_atomic_int64 0.0.1               VK_EXT_shader_module_identifier 0.0.1
    VK_EXT_shader_subgroup_ballot 0.0.1                VK_EXT_shader_subgroup_vote 0.0.1                    VK_EXT_shader_viewport_index_layer 0.0.1
    VK_EXT_subgroup_size_control 0.0.2                 VK_EXT_texel_buffer_alignment 0.0.1                  VK_EXT_tooling_info 0.0.1
    VK_EXT_transform_feedback 0.0.1                    VK_EXT_vertex_attribute_divisor 0.0.3                VK_EXT_vertex_input_dynamic_state 0.0.2
    VK_EXT_ycbcr_2plane_444_formats 0.0.1              VK_EXT_ycbcr_image_arrays 0.0.1                      VK_NV_clip_space_w_scaling 0.0.1
    VK_NV_compute_shader_derivatives 0.0.1             VK_NV_cooperative_matrix 0.0.1                       VK_NV_copy_memory_indirect 0.0.1
    VK_NV_corner_sampled_image 0.0.2                   VK_NV_coverage_reduction_mode 0.0.1                  VK_NV_cuda_kernel_launch 0.0.2
    VK_NV_dedicated_allocation 0.0.1                   VK_NV_dedicated_allocation_image_aliasing 0.0.1      VK_NV_device_diagnostic_checkpoints 0.0.2
    VK_NV_device_diagnostics_config 0.0.2              VK_NV_device_generated_commands 0.0.3                VK_NV_external_memory 0.0.1
    VK_NV_external_memory_win32 0.0.1                  VK_NV_fill_rectangle 0.0.1                           VK_NV_fragment_coverage_to_color 0.0.1
    VK_NV_fragment_shader_barycentric 0.0.1            VK_NV_fragment_shading_rate_enums 0.0.1              VK_NV_framebuffer_mixed_samples 0.0.1
    VK_NV_geometry_shader_passthrough 0.0.1            VK_NV_inherited_viewport_scissor 0.0.1               VK_NV_linear_color_attachment 0.0.1
    VK_NV_memory_decompression 0.0.1                   VK_NV_mesh_shader 0.0.1                              VK_NV_ray_tracing 0.0.3
    VK_NV_ray_tracing_invocation_reorder 0.0.1         VK_NV_representative_fragment_test 0.0.2             VK_NV_sample_mask_override_coverage 0.0.1
    VK_NV_scissor_exclusive 0.0.1                      VK_NV_shader_image_footprint 0.0.2                   VK_NV_shader_sm_builtins 0.0.1
    VK_NV_shader_subgroup_partitioned 0.0.1            VK_NV_shading_rate_image 0.0.3                       VK_NV_viewport_array2 0.0.1
    VK_NV_viewport_swizzle 0.0.1                       VK_NV_win32_keyed_mutex 0.0.2                        VK_NVX_binary_import 0.0.1
    VK_NVX_image_view_handle 0.0.2                     VK_NVX_multiview_per_view_attributes 0.0.1

**Comment by MikhailGorobets** [comment]
@IngoChow 
Try running the application through the Vulkan Configurator and see what the validation layers write or you can run the application using this flag https://github.com/DiligentGraphics/DiligentCore/blob/4c521b077308daa925c6a0f6703d53afdc07e14e/Graphics/GraphicsEngine/interface/GraphicsTypes.h#L3326. If there are no error messages, try reinstalling the GPU driver. I once had a similar problem and reinstalling the driver helped.

**Comment by TheMostDiligent** [comment]
One potential reason for the swap chain creation failure could be because your display is connected to the integrated GPU. Diligent currently does not support rendering on one GPU and presenting on another.

**Comment by IngoChow** [comment]
I checked the connected GPU info.
It is  'NVIDIA GeForce RTX 2080' , not the integrated GPU.

thanks.

Diligent Engine: Info: Using physical device 'NVIDIA GeForce RTX 2080', API version 1.3.224, Driver version 16.8.0.
Diligent Engine: Info: Extensions supported by device 'NVIDIA GeForce RTX 2080': 
    VK_KHR_16bit_storage 0.0.1                         VK_KHR_8bit_storage 0.0.1                            VK_KHR_acceleration_structure 0.0.13
    ... ...

**Comment by TheMostDiligent** [comment]
I suggest installing the Vulkan SDK and enabling validation layers. It is hard to tell why swap chain creation fails without additional information.

**Comment by IngoChow** [comment]
> @IngoChow Try running the application through the Vulkan Configurator and see what the validation layers write or you can run the application using this flag
> 
> https://github.com/DiligentGraphics/DiligentCore/blob/4c521b077308daa925c6a0f6703d53afdc07e14e/Graphics/GraphicsEngine/interface/GraphicsTypes.h#L3326
> 
> 
> If there are no error messages from the validation layers, try reinstalling the GPU driver. I once had a similar problem with an RTX 2070, and reinstalling the driver helped.

There is no error message from the validation layers. 
My driver is the latest driver.

Thanks
