### ISSUE TITLE
Increase cmake_minimum_required to 3.19

### ISSUE THREAD

**Issue by mmassing** [DiligentGraphics/DiligentCore#402]
Generator expressions for multiple configurations are only supported since cmake 3.19.
When using older cmake versions, this leads to errors such as:

CMake Error at Graphics/GraphicsTools/CMakeLists.txt:90 (target_link_libraries):
  Error evaluating generator expression:

    $<CONFIG:Release,RelWithDebInfo>

To give more actionable error messages, the cmake_minimum_required should be increased.

Probably affects other parts of DiligentEngine as well.

**Comment by TheMostDiligent** [comment]
Fixed in 36f46286b4542add345306d758490f0e86467d07
