### ISSUE TITLE
DeviceContextGLImpl::ClearDepthStencil should set glStencilMask

### ISSUE THREAD

**Issue by eugeneko** [DiligentGraphics/DiligentCore#407]
OpenGL apparently considers stencil mask when clearing the stencil. Which sucks, but it is what it is.

https://stackoverflow.com/questions/27414593/opengl-clear-the-stencil-buffer-except-for-certain-bits

> Usage warning: glClear() called with GL_STENCIL_BUFFER_BIT, but stencil write mask is 0x00. Operation will have no effect.

I can make PR but I am not sure how to approach this issue. Would it be enough to just set stencil mask thru `GLContextState::SetStencilWriteMask` in `DeviceContextGLImpl::ClearDepthStencil`, or it may cause unexpected side effects?
I have no *visible* issues after doing that.

**Comment by TheMostDiligent** [comment]
This is probably not as simple as this. `DeviceContextGLImpl::SetPipelineState` sets the stencil mask defined by the PSO, so this way you will override the mask that may have been set by the `SetPipelineState`

**Comment by TheMostDiligent** [comment]
Looks like it is necessary to store current stencil mask and then restore it similarly to how depth writes and scissor are handled.
