### ISSUE TITLE
Read-only depth tests periodically fail in Direct3D12 backend

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentCore#419]
This happens inconsistently, but quite often. The difference picture is a strong indication of GPU synchronization error.

GPU: Nvidia GeForce970 

![image](https://github.com/DiligentGraphics/DiligentCore/assets/61806567/c47c67a2-209a-4d8e-804a-fc81a290dc8f)

**Comment by eugeneko** [comment]
Is there correlation with the exact tests? Testure types probably won't matter, but what about RenderTarget vs RenderPass?

**Comment by TheMostDiligent** [comment]
Unfortunately it is quite unpredictable and not always reproducible.
It fails for one or sometimes two of the formats that are tested D16.

**Comment by TheMostDiligent** [comment]
Here are another failing pictures 

`D16`:

![ReadOnlyDepth_ReadOnlyDepthTest InRenderPass_TEX_FORMAT_D16_UNORM_FAIL_](https://github.com/DiligentGraphics/DiligentCore/assets/61806567/e2018a11-c3e3-4ebb-8b53-81140ba4a40d)

`D32_F`:

![ReadOnlyDepth_ReadOnlyDepthTest InRenderPass_TEX_FORMAT_D32_FLOAT_FAIL_](https://github.com/DiligentGraphics/DiligentCore/assets/61806567/8226d4ae-6c3b-4e42-8317-8449deda4828)
