### ISSUE TITLE
Mention in the readme which OpenGL, GLES, and Vulkan versions are being used

### ISSUE THREAD

**Issue by Xottab-DUTY** [DiligentGraphics/DiligentCore#440]
The issue name says for itself.

If not in readme, then it's worth to mention at least somewhere.

**Comment by TheMostDiligent** [comment]
What about bottom of [this section](https://github.com/DiligentGraphics/DiligentEngine#features)?

**Comment by Xottab-DUTY** [comment]
Oh my God!!!

**Comment by Xottab-DUTY** [comment]
> What about bottom of [this section](https://github.com/DiligentGraphics/DiligentEngine#features)?

That's another repository that I was unaware of. But in this issue I suggest to add the info to this repository.

**Comment by TheMostDiligent** [comment]
The first sentence of the readme refers to the main repository though, which is supposed to be the landing page of the project.
This repository is supposed to be reached from there
