### ISSUE TITLE
Emscripten `ClearRenderTarget()` issue

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentCore#441]
It seems this API accepts float RGBA, while the RTV could be in integral format... 
WebGL complains about calling the float version API on integral texture backed render target.
Not sure what's the "correct" way to fix this...

**Comment by crlf0710** [comment]
seems duplicate of #287, sorry.

**Comment by TheMostDiligent** [comment]
Duplicate of #287
