### ISSUE TITLE
Add partially resident resources to common API

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentCore#52]

**Comment by gjaegy** [comment]
Hi, just wanted to ask whether you've managed to find some time to work on that part or not ?
Thanks a lot !
Greg

**Comment by DiligentGraphics** [comment]
@gjaegy Unfortunately, no. I had no bandwidth to look at this feature yet.

**Comment by TheMostDiligent** [comment]
Remaining tasks:

- [ ] Rework unit test reference implementation to not use sparse resources
- [ ] Fix tests in D3D12
- [ ] Fix D3D11/D3D12 tests in software (WARP is supposed to support D3D12_RESOURCE_HEAP_TIER_2)
