### ISSUE TITLE
Add option to run WebGPU tests on software rasterizer

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentCore#550]
Similar to `d3d11_sw`, `d3d12_sw`, add `wgpu_sw` option that will initialize the testing framework on a software renderer.
We need this for running tests on CI.

**Comment by TheMostDiligent** [comment]
Dawn does not allow this. The only way is to modify source code.
@MikhailGorobets Please add reference to the code and close this as not planned.

**Comment by MikhailGorobets** [comment]
We need to skip all devices except the WARP device at this point:
https://github.com/google/dawn/blob/ad49eea87ac16d83539a38fc9c995555bc70ffa6/src/dawn/native/Instance.cpp#L376
