### ISSUE TITLE
WebGPU: failing tests

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentCore#553]
- [X] ShaderResourceLayout.VariableAccess (925e3f34bdbdea6f97adca871913590f3c7bbe57)
- [x] ComputeShaderTest.GenerateMips_CSInterference https://github.com/DiligentGraphics/DiligentCore/issues/572
- [X] PipelineResourceSignatureTest.UnusedNullResources #533 
 - WebGPU does not allow bind groups with null resources even if they are not used by pipeline
- [X] QueryTest.* #531
- [x] RenderPassTest.InputAttachmentWithSignature #549 
- [X] RenderStateCacheTest* [8e9c2dd](https://github.com/DiligentGraphics/DiligentCore/commit/8e9c2dd3fc4d05413ee9e1affa60bdacc33ccb00)
 -  Should be fixed by #537
- [x] StreamingBufferTest.MapUnmap #555
- [x] TextureUploaderTest* #556
- [x] ReadOnlyDepth* #554
- [X] NullResourceBindings* #538
 - WebGPU does not allow bind groups with null resources even if they are not used by pipeline
- [x] ConstantBufferReflectionTest* #503
- [x] GenerateImagesDotNetTest.GenerateCubeTexture
 -  Should be fixed by #508
- [x] DynamicTextureArray/DynamicTextureArrayResizeTest.Run/USAGE_DEFAULT__* #561

**Comment by MikhailGorobets** [comment]
Enable `ComputeShaderTest` when they fix this
https://github.com/gpuweb/gpuweb/issues/503#issuecomment-2192284247

**Comment by TheMostDiligent** [comment]
> Enable `ComputeShaderTest` when they fix this [gpuweb/gpuweb#503 (comment)](https://github.com/gpuweb/gpuweb/issues/503#issuecomment-2192284247)

OK, given that this has been open for 5 years now, we should not be expecting this will be fixed soon.
