### ISSUE TITLE
Using strings instead of const char*.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#56]
To tackle #51 , I tried reflecting HLSL shaders using D3DCompiler before sending the source code to Diligent.
Now the function that reflects the data returns it in a form of `std::vector<ShaderVariableDesc>, but since the name is a const char* , it is deleted after the function returns.

**Comment by DiligentGraphics** [comment]
Could you please clarify which function you are talking about? Did you try to use two-step workaround where you first create a shader with all static variables and use it to get all resource names?

**Comment by zlixine** [comment]
It isn't a function, I am talking about ShaderVariableDesc name member.

I didn't use the two step workaround, instead I compiled & reflected the shader using Microsoft's D3DCompiler, and I gather all the data in (std::vector<ShaderVariableDesc>) but since name is aconst char* and the vector is returned through a function all the names data are corrupted or deleted.

**Comment by DiligentGraphics** [comment]
I'm sorry, but I still not sure what the problem is.
When you create a shader, you can't store the pointer to the name in `ShaderVariableDesc`. The engine, however, creates copies of all names. So if you query the name through the created shader object (or SRB), it will return the pointer that will be correct as long as the object itself is alive.

**Comment by zlixine** [comment]
The name member in the `ShaderVariableDesc` is not being copied (or moved) correctly when initializing a vector of `ShaderVariableDesc` with another, this is due to that the name variable is a const char* not a string.
So when I try to use a function that return a vector of  `ShaderVariableDesc` all the names of each desc in the vector is corrupted.

**Comment by zlixine** [comment]
Try this code on your end:

```
std::vector<ShaderVariableDesc> GetSomeReflectionData()
{
	std::vector<ShaderVariableDesc> ResVec_;

	std::string  I1 = "Iam";
	std::string  I2 = "Being";
	std::string  I3 = "Corrupted";

	ResVec_.push_back({ I1.c_str(), SHADER_VARIABLE_TYPE_MUTABLE });
	ResVec_.push_back({ I2.c_str(), SHADER_VARIABLE_TYPE_STATIC });
	ResVec_.push_back({ I3.c_str(), SHADER_VARIABLE_TYPE_DYNAMIC });

	return ResVec_;
}
```


```
	std::vector<ShaderVariableDesc> VecVars= GetSomeReflectionData();
			
	CreationAttribs.Desc.VariableDesc = VecVars.data();
	CreationAttribs.Desc.NumVariables = VecVars.size();
```

ResVec_ vector members' names are correct, while VecVars members' names are corrupted.

**Comment by DiligentGraphics** [comment]
That is what I was trying to say: Diligent creates it's own copy of the string that you give it. If you want to use your original pointers, you need to make sure these are alive when your later access them. If you query ShaderVariableDesc from the shader you created, it will give you a structure that points to the copy of the name you gave the engine.

std::string can't be used in the interface because it will make the API bound to c++ and specific compiler. For instance, it will not be possible to build dll and use it with another compiler or even same compiler that doesn't use the same runtime library, let alone other languages (even c).

**Comment by DiligentGraphics** [comment]
There is a bug in your code: all your strings are destroyed when you exit `GetSomeReflectionData()` function, and elements of `VecVars` array reference dead objects. Diligent API has nothing to do with the correctness of the client program. You need to make sure that all your strings are alive when you exit the function. Here is one way:

```
std::vector<ShaderVariableDesc> GetSomeReflectionData(std::unordered_set<std::string>& StringPool)
{
	std::vector<ShaderVariableDesc> ResVec_;

	auto I1 = StringPool.emplace("Your program").first;
	auto I2 = StringPool.emplace("must be").first;
	auto I3 = StringPool.emplace("well formed").first;

	ResVec_.push_back({ I1->c_str(), SHADER_VARIABLE_TYPE_MUTABLE });
	ResVec_.push_back({ I2->c_str(), SHADER_VARIABLE_TYPE_STATIC });
	ResVec_.push_back({ I3->c_str(), SHADER_VARIABLE_TYPE_DYNAMIC });

	return ResVec_;
}

        std::unordered_set<std::string>& StringPool;
	std::vector<ShaderVariableDesc> VecVars= GetSomeReflectionData(StringPool);
			
	CreationAttribs.Desc.VariableDesc = VecVars.data();
	CreationAttribs.Desc.NumVariables = VecVars.size();
```

**Comment by zlixine** [comment]
Also, is there any good reason to use C strings "const char*" instead of C++ strings "std::string"?

**Comment by DiligentGraphics** [comment]
I don't understand why Diligent API should be responsible for fixing this very specific bug in your code. The API takes pointers to the data and assumes that data is correct. If you call Diligent API with corrupted data, it's definitely not the engine's fault.

Making `std::string` part of the API means that memory allocation and deallocation as well as all the set of operations intrinsic to `std::string` becomes part of the API. That also mean that c runtime library also becomes part of the API. That means that STL implementation becomes part of the API. In particular, that means that if you build a DLL, you will only be able to use this DLL with the exact same compiler and exact same build settings, and exact same STL implementation. You will not be able to build the DLL and use it with other compilers let alone other languages. In particular, making C api is one of the requested features and using `std::string` will make it impossible. 
What if the application doesn't want to use `std::string` and uses another string management strategy.
The way the application handles its data is completely orthogonal to the engine, so yes, there is a lot of good reasons.
