### ISSUE TITLE
Can't copy GL Texture2D to Cube Map Face

### ISSUE THREAD

**Issue by rbnpontes** [DiligentGraphics/DiligentCore#563]
**OS:** Windows 11 22631.3880
**Build tools:** Visual Studio 2022 Debug x64 + 3.27.3
**GPU:** NVIDIA GeForce RTX 3050 Laptop GPU. Driver Version: 31.0.15.5222
**Diligent Version:** v2.5.4
**Backend:** OpenGL
**Error**: Failed to bind texture to target 34069

### How to reproduce
1. Start diligent with OpenGL backend
2. Create a Texture with the properties above and fill with some data:
**Type:** RESOURCE_DIM_TEX_2D
**Usage:** USAGE_DEFAULT
**Width&Height:** Some random size, Width and Height must be the same
**Format:** Choose your own, in my case was TEX_FORMAT_RGBA8_UNORM
3. Create a Texture with the properties above:
**Type:** RESOURCE_DIM_TEX_CUBE
**Usage::** USAGE_DEFAULT
**Width&Height:** Same of Texture 2D
**Format:** Same of Texture 2D
4. Call `CopyTexture` method of `IDeviceContext` to copy Texture 2D to Cube Map face
5. Crash!!! Due to `GLContextState.cpp` assertion at line [243](https://github.com/DiligentGraphics/DiligentCore/blob/c4df74bb2a65141c5a5cc0f38647d8cb3f7560d8/Graphics/GraphicsEngineOpenGL/src/GLContextState.cpp#L243)

### Workaround
At `TextureCube_GL.cpp` i patched the line [301](https://github.com/DiligentGraphics/DiligentCore/blob/c4df74bb2a65141c5a5cc0f38647d8cb3f7560d8/Graphics/GraphicsEngineOpenGL/src/TextureCube_GL.cpp#L301)
**From:** `GLState.BindTexture(-1, CubeMapFaceBindTarget, GetGLHandle());`
**To:** `GLState.BindTexture(-1, GL_TEXTURE_CUBE_MAP, GetGLHandle());`
And it worked, so far I haven't had any problems

**Comment by TheMostDiligent** [comment]
This change does not look right. There are 6 cubemap bind targets for each cubemap face (`GL_TEXTURE_CUBE_MAP_POSITIVE_X`, `GL_TEXTURE_CUBE_MAP_NEGATIVE_X`, etc.)
What this code does is setting the appropriate face for depending on the array layer. What your change does is setting the same bind target irrespective of the array layer.
You may not be getting the error, but you are certainly not copying the data to the right face either.

Can you provide a code to reproduce this problem?

**Comment by rbnpontes** [comment]
I tried to simulate this problem, so I took the Tutorial 03 sample and modified it a little bit.
![image](https://github.com/user-attachments/assets/e3f87d2f-e044-4c7b-9da6-6faacd110a32)
It actually worked correctly, but I noticed in my personal build that I don't have this extension: **GL_ARB_copy_image**
And the copy texture operation doesn't execute this part
![image](https://github.com/user-attachments/assets/c9abe17a-987c-49d0-aca0-c67d8ba46f91)
So I disabled this part to simulate the problem, and engine show this
![image](https://github.com/user-attachments/assets/a21a9abf-7685-47d6-adfb-73cd96b7dbc7)
Idk if did something wrong or miss something.
