### ISSUE TITLE
HLSL2GLSL lib runtime error on android arm64-v8a ABI

### ISSUE THREAD

**Issue by dom607** [DiligentGraphics/DiligentCore#59]
```code A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7da0becff0 in tid 27707 (Thread-2), pid 27683 (gentandroidtest)```

Runtime error occurred when "uint2x1" key pair insert.
https://github.com/DiligentGraphics/DiligentCore/blob/25ff48f701c1193d06df740f5f937ea4b8ee2b91/Graphics/HLSL2GLSLConverterLib/src/HLSL2GLSLConverterImpl.cpp#L514

"armeabi-v7a" work correctly. 

I already questioned this with mail. But for better issue management and describe error detail, I write it here too.

Tested device : Xiaomi POCO F1(android 9.0) and Galaxy note 4(android 6.0)
IDE : android studio 3.3.1

**Comment by DiligentGraphics** [comment]
I guess I've seen similar issue somewhere else. Would you be able to try release build? As far as I remember, for some reason it was crashing in debug build only.

**Comment by dom607** [comment]
Thank you. I'll test it on Monday.

**Comment by dom607** [comment]
Working fine with release build. Close the issue. Thank you.

**Comment by DiligentGraphics** [comment]
Ok. This should work in debug build too, but I'm still not sure what is the cause of the problem here.
