### ISSUE TITLE
[bug] d3d11: DvpVerifyCommittedResources() fail if bind same UAV to multiple Slots  

### ISSUE THREAD

**Issue by WangHoi** [DiligentGraphics/DiligentCore#591]
DvpVerifyCommittedResources(): Compare local Commited d3d11Uavs with `CSGetUnorderedAccessViews` failed.

After inspect result of `CSGetUnorderedAccessViews`, I found early uav binding slot will reset to NULL, 

----

The bug is not related to application code. 

Just two `Dispatch`, refers same UAV, 
but bound to different Slot.

The bug maybe lives in Engine's state tracking code.

**Comment by WangHoi** [comment]
I found this:

[Same resource is not allowed to be set in different UAVs](https://issues.angleproject.org/issues/42261718)

**Comment by TheMostDiligent** [comment]
This behavior is invalid in Direct3D11: you can only bind resource once for output:

```
D3D11 ERROR: ID3D11DeviceContext::CSSetUnorderedAccessViews: The UnorderedAccessView at slot 0 overlaps with the UnorderedAccessView at slot 1. It is not possible to write to the same Subresources (and PlaneSlice if applicable) at the same time. [ STATE_SETTING ERROR #2097402: DEVICE_CSSETUNORDEREDACCESSVIEWS_INVALIDVIEW]
```

**Comment by WangHoi** [comment]
With current Api, It's not easy to manually unbind the uav from previous slot.
Either get underline d3d device context impl or calling InvalidStates.
 
To work around this problem, i have changed local fork's d3d11 impl to unbind unused slots  before bind changed slot.

Anyway, only d3d11 need this hack.

**Comment by TheMostDiligent** [comment]
If you use two textures, you should have two SRBs that reference each one for output. When you bind the second one, the first one should be unbound.

**Comment by TheMostDiligent** [comment]
Essentially, an SRB can only have one texture that is set for output

**Comment by WangHoi** [comment]
I just need to bind the uav to new slot position, not change resource state.
Current Api is not easy to do so.

With resource transition mode AUTO, i assume the unbind rebind step can be done by the engine.

Because if I just change the uav variable definition order in *hlsl*, the assert error can go away.
Quite strange if engine runtime behavior depends on this.

**Comment by TheMostDiligent** [comment]
When you bind an SRB, the engine unbinds all resources that need to be unbound, it is automatic.

I don't fully understand what exactly you are doing - can you provide a sequence of commands with shaders that you are using?

**Comment by WangHoi** [comment]
AFAIK, in Bgfx, i just need to describe current Dispatch's resource bindings, every draw command description is stateless.

Not worry about unbind uav to cleanup previous Dispatch's mess.

**Comment by WangHoi** [comment]
Sorry, i will provide an example later tomorrow.

**Comment by WangHoi** [comment]
This is the example to produce above situation:
[uav_slot.zip](https://github.com/user-attachments/files/16473076/uav_slot.zip)

## What the sample does
Dispatch three compute kernel:
1. Write to uav `Buffer0` and `Buffer1` 
2. Read and write `Buffer0`
3. Read and write `Buffer1`

## Build and run
- CMakeLists.txt - Set `DILIGENT_ROOT` to DiligentEngine directory.
- After build, set executable runtime directory to the `assets` subfolder.

## Problem
Assert error only in d3d11 backend, in Step.3

**Comment by WangHoi** [comment]
Hi, could you please have a look at the example.

Is this a mis-use of Diligent API, or a real bug>

**Comment by TheMostDiligent** [comment]
This is a real issue

**Comment by WangHoi** [comment]
Hey, two nested for loop and `CSSetUnorderedAccessViews(null)` may not be a good idea. 
Change UAV Binding is on runtime critical path.

You may only change the validation layer, what i previous thought:

- Only tracking [NumUav]
- Change DvpVerifyXXX, Do not cache whole `CommittedD3D11ResourcesArr[SHADER_TYPE_COMPUTE]`,
populate it dynamically, for example:

Code from DXVK:
```cpp
  template<typename ContextType>
  void STDMETHODCALLTYPE D3D11CommonContext<ContextType>::CSGetUnorderedAccessViews(
          UINT                              StartSlot,
          UINT                              NumUAVs,
          ID3D11UnorderedAccessView**       ppUnorderedAccessViews) {
    D3D10DeviceLock lock = LockContext();

    for (uint32_t i = 0; i < NumUAVs; i++) {
      ppUnorderedAccessViews[i] = StartSlot + i < m_state.uav.views.size()
        ? m_state.uav.views[StartSlot + i].ref()
        : nullptr;
    }
  }
```

Then, no price to pay when doing UAV bindings (in release build), 
cost only in validation.

**Comment by WangHoi** [comment]
Need `CSSetUnorderedAccessViews(null)` to suppress warning.

The problem is to quickly check this rare condition, not to check it with two for loops in  every call to ` DeviceContextD3D11Impl::BindCacheResources()`.

**Comment by TheMostDiligent** [comment]
This will not be a problem. First of all, in any application there are only a handful of `CSSetUnorderedAccessViews` calls in a frame.
Second, the loop only runs for slots that are not being set and checks other slots, so there will be not too many operations.

**Comment by WangHoi** [comment]
😀Thank you so much.

It works now, no error on complex compute flows.
