### ISSUE TITLE
Direct12 crash on CommitShaderResources with Release build

### ISSUE THREAD

**Issue by senevoldsen** [DiligentGraphics/DiligentCore#68]
I have the following function for drawing:

```c++
void SubmitDraw(Context &ctx, const GraphicsPipelineDesc& gpd, const DrawAttribs& drawAttrs)
{
    IPipelineState* pso = nullptr;
    IShaderResourceBinding* srb = nullptr;
    GetPSO(ctx, gpd, &pso, &srb);

    ctx.pContext->SetPipelineState(pso);
    ctx.pContext->CommitShaderResources(srb, RESOURCE_STATE_TRANSITION_MODE_TRANSITION);

    DrawAttribs copy(drawAttrs);
    copy.Flags = DRAW_FLAG_VERIFY_STATES;
    ctx.pContext->Draw(copy);
}
```

I have isolated this to be the only enabled function making draw calls. The `GetPSO` function creates/retrieves cached PSO/SRB pairs. When I run this in both debug/release mode on OpenGL and D3D11 it runs fine. It also runs without issue when I run it on D3D12 in debug mode, but in Release mode it crashes quickly. Got it down to a few frames now (around 4, the more inefficient I make the program the more *frames* can run before crashing).

The error I get is an access violation reading something in the call to `CommitShaderResources`. Diligent is being diligent and outputs the following: `Diligent Engine: ERROR: Failed to suballocate region for dynamic descriptors` which lead me onto a cold trail here: https://github.com/DiligentGraphics/DiligentCore/blob/b5ac1fd1cc897c24c8908f365c072bd016baf256/Graphics/GraphicsEngineD3D12/src/DescriptorHeap.cpp#L430 . I am only using one thread at the moment, and only one "immediate" context `pContext`.

If it was because I keep allocating resources then the debug build would suffer from the same, and the memory usage remains constant in all runs (that don't crash). GetPSO creates a total of 7 PSO/SRB pairs on the first frame, and then none the rest of the time, they are reused. If I comment out the `CommitShaderResources` call, it does not crash. If I change the transition mode to none and manually transition them elsewhere, e.g. inside GetPSO, it still crashes here on the call to CommitShaderResources.

Am I supposed to transition the resources out or something? But then it would also crash in debug?

**Comment by DiligentGraphics** [comment]
Try to increase the size of the GPU descriptor heap:
https://github.com/DiligentGraphics/DiligentEngine/blob/master/Projects/Asteroids/src/asteroids_DE.cpp#L115
At the end of the frame Diligent prints API-specific  resource usage statistics. For D3D12 this includes descriptor heap usage statistics:
```
Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER     GPU heap max allocated size (static|dynamic): 22/128 (17.19%) | 16/1920 (0.83%).
Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV GPU heap max allocated size (static|dynamic): 56/16384 (0.34%) | 64/32768 (0.20%).
```
Try to make sure that utilization is not close to 100%.

**Comment by senevoldsen** [comment]
Increasing the descriptor values did not change anything, but by decreasing I could get it to reliably crash in debug mode too. I am only using more than 1% of two resources:

```
Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER     GPU heap max allocated size (static|dynamic): 0/1024 (0.00%) | 832/1024 (81.25%).
Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV GPU heap max allocated size (static|dynamic): 0/16384 (0.00%) | 1024/8192 (12.50%).
```

I am creating ~15 textures and assigning each their own sampler (I will move to only two static samplers later). If I move to using only a single static sampler, I get this

```Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER     GPU heap max allocated size (static|dynamic): 0/1024 (0.00%) | 0/1024 (0.00%).```

and no crashes. I then move to a single dynamic sampler only, the 15 textures being assigned the same sampler. I get same results as first:

```Diligent Engine: Info: D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER     GPU heap max allocated size (static|dynamic): 0/1024 (0.00%) | 832/1024 (81.25%).```

I tried increasing the sampler count, but apparently the defaults are maximum (since it automaticall adds 1024 to your input?). I then tried reducing it, and that made the issue replicate in Debug mode.

```EngD3D12Attribs.GPUDescriptorHeapSize[1] = 256;
EngD3D12Attribs.GPUDescriptorHeapDynamicSize[1] = 256;```

I found this note in the comments: "In D3D11, 4096 unique sampler state objects can be created on a device at a time". Not sure what the numbers are for D3D12, but I am guessing it is more than 1, so I must be doing something wrong?

**Comment by DiligentGraphics** [comment]
You are in fact using 81.25% of dynamic sampler heap space, so just few more draw calls and you will run out of sampler descriptors. The problem is that when you label shader variable as dynamic, the descriptor for this variable is allocated at every draw call. So even though you have 15 textures, if you issue 200 draw calls, it will allocate 200 dynamic descriptors. Also descriptors will be locked for few frames while GPU is not done with them. So 200 draw calls will require somewhat 200*3 dynamic descriptors.
Dynamic shader resource variables are easiest to use, but are the slowest. Most of the time you don't need them. With samplers, you almost never ever need to change the sampler dynamically, so static sampler compiled at shader creation time will work almost all the time and should be used whenever possible. There is no limitation on the number of static samplers. In your second example dynamic sampler descriptor usage is 0%, which it should almost always be.
D3D12 limits the number of descriptor samples in one heap by 2048. This number is split between dynamic allocations used for dynamic variables and static part allocated for SRBs.

**Comment by senevoldsen** [comment]
Thank you, I think that explains it my issue. And I have 548 draw calls per frame using that shader. I am guessing the difference between debug and release comes to circumstance with debug being just slow enough not to cause this issue?

I only know the proper sampler to use at runtime - the original interface used OpenGL state changes. The sampler to use depends on 2^3 = 8  (maybe 2^4) different possibilities. So what is the proper way to do it? Should I just create them all at shader creation time. Then how do I use the right one at the call? Or should I create 8 almost identical shaders too, increasing number of PSO also by factor 8?

Would something like this (from https://docs.microsoft.com/en-us/windows/desktop/direct3d12/resource-binding-in-hlsl ) work / be "a proper" approach?

```hlsl
Texture2D texture;
sampler samplers[7] : register(s0);
texture.Sample(samplers[samplerID], texCoords);
```

Replacing sampler with SamplerState, and passing samplerID in a cbuffer?

**Comment by DiligentGraphics** [comment]
That's correct. With debug being slower, the samplers become available faster as CPU does not produce enough commands to saturate the GPU.
The order of preferences is this:
1. Everything is static at set up at PSO/Shader creation stage (static samplers, static shader shader resources).
2. Mutable resources: if you know you may need 15 combinations of textures/samplers, you create one SRB per combination and bind the right one at run time
3. Dynamic variables - last resort. This should only be used when a resource is truly changing randomly and a lot at run time. This has high run-time overhead.

Binding all samplers once and then selecting them at run-time in the shader is also a good and recommended approach. Creating 8 almost identical PSOs is not optimal too as switching PSOs is expensive.

Please note that Diligent targets next-gen APIs. Using it efficiently requires rethinking the rendering architecture. Creating PSOs at run-time, late-binding resources, fine-grain state management is not efficient. The idea of next-gen APIs that Diligent also exposes is to prepare everything ahead of time: PSOs, resource bindings, etc. which will significantly reduce the amount of work at run time.

**Comment by senevoldsen** [comment]
I will change my implementation to use static/mutable samplers. I have read on the next-gen designs, and do realize the need to construct as much up front.

But the library I am porting for was designed with OpenGL state-based API in mind and is therefore very liberal with what it allows/does at runtime. For instance it makes blend factors. There are 4 blend factors with 11 possibilities each, thus 11^4: https://github.com/memononen/nanovg/blob/master/src/nanovg_gl.h#L1229 . Though most usage of the library will symmetric giving 11^2. In practice the original demo sample only uses one or two. The problem is knowing in advance.

So I am thinking of adding a function on top of the original API to allow you to tell in advance what blending factor combinations you are actually going to use later. Or maybe a "dry-run" where it doesn't do any drawing but gather what it would need to do before hand.

Thank you for your help. I am closing this issue since it has been resolved as user error :)

**Comment by DiligentGraphics** [comment]
You are not the only one who experiences issues related to dynamic variables. it is the fastest way to get things running especially when porting from older APIs, but also the slowest way. I will put together some perf guide to help the library users.
