### ISSUE TITLE
Compiling HLSL shader error in OpenGL side only.

### ISSUE THREAD

**Issue by zlixine** [DiligentGraphics/DiligentCore#86]
It is worth noting it doesn't occur on any other API even Vulkan.

Error details:
```
[FATAL_ERROR] [GraphicsEngine] Missing argument type
>  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >  >

/*
Defines:
#define NE_USE_UV
#define NE_USE_NORMALS
#define NE_USE_TANGENTS
#define NE_USE_DEF_CAMERA
#define NE_OUT_FRAG_POS

*/
//#define NE_USE_UV
//#define NE_USE_NORMALS
//#define NE_USE_TANGENTS
//#define NE_USE_DEF_CAMERA
//#define NE_OUT_FRAG_POS

struct VertexInputType
{
    float4 Position : ATTRIB0;
#ifdef NE_USE_UV
^
    float2 TexCoord : ATTRIB1;
#endif
#ifdef NE_USE_NORMALS
    float3 Normals : ATTRIB2;
<  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <  <
```

**Comment by zlixine** [comment]
Also is there anyway to return certain codes through DiligentMassageCallback that indicate the type of the error, because I want to ignore some fatal errors as error in shader compilation but I don't know how to know its type from the other fatal errors.

**Comment by DiligentGraphics** [comment]
Yes, it is the limitation of GLSL->HLSL converter.
http://diligentgraphics.com/diligent-engine/shader-converter/
A workaround that should work is to define a nested structure:

```hlsl
#ifdef NE_USE_UV
struct TexCoordInputType
{
   float2 UV : ATTRIB0;
};
#else
struct TexCoordInput
{
};
#endif

struct VertexInputType
{
   TexCoordInputType TexCoordInput;
};
```
Right now there is no way to detect shader compilation error. I guess you should try to avoid shader compilation errors at run time. I guess you may use FileName to ignore errors originating in certain files

**Comment by zlixine** [comment]
I heard that modern OpenGL (4.5) can use Spir-V instead of GLSL, can I force diligent to use it?
I can't get rid of the macros, my shader compilation system kinda depends on them.

**Comment by DiligentGraphics** [comment]
That is correct. On the other hand if you platform supports OpenGL4.6 it certainly supports Vulkan and there is no need to use OpenGL backend.
The main purpose of OpenGL backend is backwards compatibility with old devices (GLES3.0, OpenGL4.1), so there is no point in enabling SPIR-V. Like I said, you can use Vulkan back-end.
Also, there is no need in getting rid of macros completely, you just need to rewrite structures little bit to make them work with converter.
