### ISSUE TITLE
OpenGL Linux interoperability: Segmentation fault on IDeviceContext::SetRenderTargets

### ISSUE THREAD

**Issue by isushik94** [DiligentGraphics/DiligentCore#88]
Hi.

I was working with a `GLXPbuffer` for windowless rendering. I faced some issues with `IDeviceContext::ClearRenderTarget` and viewport's settings and finally got a point that a method `IDeviceContext::SetRenderTargets` is necessary for setting `m_IsDefaultFramebufferBound` of GL implementation. So I called it and my application crashed with a `Segfault` error. After some time I found that an `IDeviceContext` instance was without specified `ISwapChain` but a line:
`VERIFY(m_pSwapChain, "Swap chain is not initialized in the device context")`
from `DeviceContextBase` class didn't do anything. I guess the app crashed  at this cast or a bit later on this method calling: `m_pSwapChain->GetCurrentBackBufferRTV()`.

So the issue's gone with this call `IDeviceContext::SetSwapChain(m_pSwapChain);` after creating a proxy swap chain instance.

And it seems this guide is out of date for v2.4.b release: http://diligentgraphics.com/diligent-engine/native-api-interoperability/openglgles-interoperability/.

The issue isn't urgent but I hope it will help someone as it's hard to handle segfaults.

**Comment by DiligentGraphics** [comment]
Hi (sorry for longer response),
Could you please clarify what problem exactly you faced? The guide does say that you need to set the proxy swap chain if you are planning to work with the default frame buffer. Speaking about `VERIFY`, did you build debug configuration?

**Comment by isushik94** [comment]
I'm new with your framework and I have a lack of knowledge about it.

> Could you please clarify what problem exactly you faced?
The problem was that I didn't set a swap chain instance and it was probably NULL.

> The guide does say that you need to set the proxy swap chain if you are planning to work with the default frame buffer.
Yes, I've just found this but there is no code sample so it seems I missed it earlier.

> Speaking about VERIFY, did you build debug configuration?
No, I've built a DiligentCore library with release configuration. So know I'll prepare a debug version. Thanks.

**Comment by DiligentGraphics** [comment]
OK, I see. Updated the guide to remove the confusion. Feel free to open another issue / reopen this one if you have more questions.
