### ISSUE TITLE
Feature Request: ClearTexture() support.

### ISSUE THREAD

**Issue by thatname** [DiligentGraphics/DiligentCore#91]
Both OGL & D3D has ClearTexture(). It is capable to clear all layers of volume texture with just one call, thus useful for voxel based cone tracing GI algorithms (e.g. VXGI ).

**Comment by DiligentGraphics** [comment]
In fact, there is no such command in D3D11/D3D12, which provide `ClearRenderTargetView`, `ClearDepthStencilView` and `ClearUnorderedAccessView` instead. In OpenGL, there is `glClearTexSubImage` command that is only available in desktop gl 4.4 and is unavailable in OpenGLES altogether. Vulkan does offer image clearing commands.
This would indeed be convenient, but may not be as straightforward to implement as it seems.

**Comment by DiligentGraphics** [comment]
Diligent is a low-level API and this functionality can be implemented with existing commands.
