### ISSUE TITLE
NVIDIA Jetson TX2 - Failed to compile samples , XCB error

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#96]
With OpenGL backend compiled when started to compile Samples geting the follow problem:

[ 86%] Linking CXX executable AntTweakBarSample
../../../DiligentTools/External/lua-5.2.3/libLua.a(loslib.c.o): In function `os_tmpname(lua_State*)':
loslib.c:(.text+0x2f0): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: ../../../Common/NativeApp/Linux/libXCBKeySyms.a(xcb_keysyms.c.o): undefined reference to symbol 'xcb_get_setup'
//usr/lib/aarch64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/build.make:103: recipe for target 'DiligentSamples/Samples/AntTweakBar/AntTweakBarSample' failed
make[2]: *** [DiligentSamples/Samples/AntTweakBar/AntTweakBarSample] Error 1
CMakeFiles/Makefile2:1882: recipe for target 'DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/all' failed
make[1]: *** [DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

XCB is installed , its seems maybe like missing linkage library that is not set in the make file for this project

**Comment by olegviz** [comment]
I added the -lxcb to the linkage makefile and this seems make it better 

but now there is another error 

[ 86%] Linking CXX executable AntTweakBarSample
../../../DiligentTools/External/lua-5.2.3/libLua.a(loslib.c.o): In function `os_tmpname(lua_State*)':
loslib.c:(.text+0x2f0): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmFreeDevice'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmFreeDevices'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmMap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDeviceNameFromFd2'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmCloseOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmUnmap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDevices2'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmOpenOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDevice2'
collect2: error: ld returned 1 exit status
DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/build.make:103: recipe for target 'DiligentSamples/Samples/AntTweakBar/AntTweakBarSample' failed
make[2]: *** [DiligentSamples/Samples/AntTweakBar/AntTweakBarSample] Error 1
CMakeFiles/Makefile2:1882: recipe for target 'DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/all' failed
make[1]: *** [DiligentSamples/Samples/AntTweakBar/CMakeFiles/AntTweakBarSample.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by olegviz** [comment]
and this was solved by these magic :

cd /usr/lib/aarch64-linux-gnu/
sudo ln -sf tegra/libGL.so libGL.so

**Comment by olegviz** [comment]
OpenGL backend compiled and working !

**Comment by DiligentGraphics** [comment]
Reopen the issue for now as XCB should probably be added to the link list. Need to double check. 
Not sure about libGL problem though as well as its solution.

**Comment by DiligentGraphics** [comment]
https://github.com/DiligentGraphics/DiligentEngine/commit/030cbb3db06c3361e3a5dcfd8dc94ee2231531b6 should also fix this issue. Please reopen if it still doesn't build
