### ISSUE TITLE
Vulkan backend support for Linux ARM version

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#97]
When compiling Diligent on Linux ubuntu LTS version for ARM (NVIDIA jetson xaviar)

The compilation failed on linking to libvulkan.so that is found in 
https://github.com/DiligentGraphics/DiligentCore/tree/master/External/vulkan/libs

this is probably because its a x86 version of the library and not ARM

**Comment by DiligentGraphics** [comment]
Yes, x86 library will certainly not work on ARM. Vulkan SDK for Linux only provides prebuilt library for x86.

Could you try to build the loader for ARM from source (I don't have ARM Linux for testing):
https://github.com/KhronosGroup/Vulkan-Loader

**Comment by olegviz** [comment]
Yes I"ll try it  .

**Comment by TheMostDiligent** [comment]
Diligent does not rely on pre-built libraries anymore and uses Volk for Vulkan loading.
