### ISSUE TITLE
Red Hat Linux compilation error

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#98]
The follow error happend when started to compile at Red Hat Linux gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

Scanning dependencies of target Diligent-Common
[  2%] Building CXX object DiligentCore/Common/CMakeFiles/Diligent-Common.dir/src/BasicFileStream.cpp.o
[  2%] Building CXX object DiligentCore/Common/CMakeFiles/Diligent-Common.dir/src/DataBlobImpl.cpp.o
[  2%] Building CXX object DiligentCore/Common/CMakeFiles/Diligent-Common.dir/src/DefaultRawMemoryAllocator.cpp.o
[  3%] Building CXX object DiligentCore/Common/CMakeFiles/Diligent-Common.dir/src/FixedBlockMemoryAllocator.cpp.o
/home/btx/GitHub/DiligentEngine/DiligentCore/Common/src/FixedBlockMemoryAllocator.cpp: In constructor ‘Diligent::FixedBlockMemoryAllocator::FixedBlockMemoryAllocator(Diligent::IMemoryAllocator&, size_t, Diligent::Uint32)’:
/home/btx/GitHub/DiligentEngine/DiligentCore/Common/src/FixedBlockMemoryAllocator.cpp:37:45: error: no matching function for call to ‘std::unordered_set<long unsigned int, std::hash<long unsigned int>, std::equal_to<long unsigned int>, Diligent::STDAllocator<long unsigned int, Diligent::IMemoryAllocator> >::unordered_set(Diligent::STDAllocatorRawMem<long unsigned int>)’
         m_NumBlocksInPage   (NumBlocksInPage)
                                             ^
/home/btx/GitHub/DiligentEngine/DiligentCore/Common/src/FixedBlockMemoryAllocator.cpp:37:45: note: candidates are:
In file included from /usr/include/c++/4.8.2/unordered_set:48:0,
                 from /home/btx/GitHub/DiligentEngine/DiligentCore/Common/interface/FixedBlockMemoryAllocator.h:31,
                 from /home/btx/GitHub/DiligentEngine/DiligentCore/Common/src/FixedBlockMemoryAllocator.cpp:25:
/usr/include/c++/4.8.2/bits/unordered_set.h:178:7: note: std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::initializer_list<typename std::_Hashtable<_Value, _Value, _Alloc, std::__detail::_Identity, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::is_default_constructible<_Hash>, std::is_copy_assignable<_Hash>, std::__detail::__is_noexcept_hash<_Tp, _Hash> > >::value, true, true> >::value_type>, std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = long unsigned int; _Hash = std::hash<long unsigned int>; _Pred = std::equal_to<long unsigned int>; _Alloc = Diligent::STDAllocator<long unsigned int, Diligent::IMemoryAllocator>; typename std::_Hashtable<_Value, _Value, _Alloc, std::__detail::_Identity, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::is_default_constructible<_Hash>, std::is_copy_assignable<_Hash>, std::__detail::__is_noexcept_hash<_Tp, _Hash> > >::value, true, true> >::value_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<long unsigned int>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<long unsigned int>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = Diligent::STDAllocator<long unsigned int, Diligent::IMemoryAllocator>]
       unordered_set(initializer_list<value_type> __l,

**Comment by olegviz** [comment]
error: no matching function for call to ‘std::unordered_set<long unsigned int, std::hash, std::equal_to, Diligent::STDAllocator<long unsigned int, Diligent::IMemoryAllocator> >::unordered_set(Diligent::STDAllocatorRawMem)’
m_NumBlocksInPage (NumBlocksInPage)

**Comment by DiligentGraphics** [comment]
Can you update gcc? 4.8 is pretty outdated, the latest version is 9.1

**Comment by olegviz** [comment]
Not sure , its a Red Hell hhh , its like nuclear shelter

**Comment by olegviz** [comment]
To upgrade GCC need to install Development Tool Kit and this require Subscription , and as I understand is not for free . 
OMG its a ... BUNKER

**Comment by DiligentGraphics** [comment]
Installing gcc on a Linux is not free? Hmm, this is really odd. gcc 4.8 is really old and only provides experimental support for c++ 11

**Comment by olegviz** [comment]
Red Hat linux is not open source and not free. 
Ok , Ill use Fedora to compile on other machine and will try to run on Red Hat for now its will be good enough.

**Comment by olegviz** [comment]
I will check it again , don’t understand what is free , need to open developer account

**Comment by olegviz** [comment]
Ok , so installed the gcc 8.3 and its compiled successfuly
