### ISSUE TITLE
Linux compile error

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentCore#99]
I"m geting this error when integrating with Diligent from my application

./../../Vision/Runtime/DiligentEngine/DiligentCore/Graphics/GraphicsEngine/interface/GraphicsTypes.h:1293:19: error: #if with no expression
 #if PLATFORM_LINUX
                   ^

its not supposed to be #ifdef ?

**Comment by DiligentGraphics** [comment]
Hm.. Technically, yes, but this should also work. There are many other places where constructs like below are used:

```cpp
#if PLATFORM_WIN32 || PLATFORM_LINUX || PLATFORM_ANDROID
```

Which platform/compiler do you use?

**Comment by olegviz** [comment]
This is only first error , there also others of this type 

I"m compiling on VirtualBox with ubuntu linux ,gcc  8.3
maybe its because I don"t use -std=c++11 in my application when include diligent headers

**Comment by DiligentGraphics** [comment]
Yes, this may be the case. This is only for your project, Diligent itself builds fine?

**Comment by olegviz** [comment]
Yes the diligent is builds fine .

**Comment by DiligentGraphics** [comment]
Can you try to build it with -std=c++11?

**Comment by olegviz** [comment]
its my mistake :

I did : #define PLATFORM_LINUX
but
its should be #define PLATFORM_LINUX 1

its a little confusing

**Comment by DiligentGraphics** [comment]
Yes, this is in fact mentioned in [integration instructions](https://github.com/DiligentGraphics/DiligentEngine#your-project-does-not-use-cmake).
I also started [Troubleshooting guide](https://github.com/DiligentGraphics/DiligentEngine/blob/master/Troubleshooting.md) to help fix most common issues.
